/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the ActionEmailDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionEmailDestination{}

// ActionEmailDestination struct for ActionEmailDestination
type ActionEmailDestination struct {
	// Whether to notify the email recipients when the alert is resolved
	NotifyOnResolve *bool `json:"notifyOnResolve,omitempty"`
	// Email addresses to send alert to
	Emails []string `json:"emails,omitempty"`
}

// NewActionEmailDestination instantiates a new ActionEmailDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionEmailDestination() *ActionEmailDestination {
	this := ActionEmailDestination{}
	var notifyOnResolve bool = false
	this.NotifyOnResolve = &notifyOnResolve
	return &this
}

// NewActionEmailDestinationWithDefaults instantiates a new ActionEmailDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionEmailDestinationWithDefaults() *ActionEmailDestination {
	this := ActionEmailDestination{}
	var notifyOnResolve bool = false
	this.NotifyOnResolve = &notifyOnResolve
	return &this
}

// GetNotifyOnResolve returns the NotifyOnResolve field value if set, zero value otherwise.
func (o *ActionEmailDestination) GetNotifyOnResolve() bool {
	if o == nil || IsNil(o.NotifyOnResolve) {
		var ret bool
		return ret
	}
	return *o.NotifyOnResolve
}

// GetNotifyOnResolveOk returns a tuple with the NotifyOnResolve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionEmailDestination) GetNotifyOnResolveOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnResolve) {
		return nil, false
	}
	return o.NotifyOnResolve, true
}

// HasNotifyOnResolve returns a boolean if a field has been set.
func (o *ActionEmailDestination) HasNotifyOnResolve() bool {
	if o != nil && !IsNil(o.NotifyOnResolve) {
		return true
	}

	return false
}

// SetNotifyOnResolve gets a reference to the given bool and assigns it to the NotifyOnResolve field.
func (o *ActionEmailDestination) SetNotifyOnResolve(v bool) {
	o.NotifyOnResolve = &v
}

// GetEmails returns the Emails field value if set, zero value otherwise.
func (o *ActionEmailDestination) GetEmails() []string {
	if o == nil || IsNil(o.Emails) {
		var ret []string
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionEmailDestination) GetEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.Emails) {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *ActionEmailDestination) HasEmails() bool {
	if o != nil && !IsNil(o.Emails) {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []string and assigns it to the Emails field.
func (o *ActionEmailDestination) SetEmails(v []string) {
	o.Emails = v
}

func (o ActionEmailDestination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionEmailDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NotifyOnResolve) {
		toSerialize["notifyOnResolve"] = o.NotifyOnResolve
	}
	if !IsNil(o.Emails) {
		toSerialize["emails"] = o.Emails
	}
	return toSerialize, nil
}

type NullableActionEmailDestination struct {
	value *ActionEmailDestination
	isSet bool
}

func (v NullableActionEmailDestination) Get() *ActionEmailDestination {
	return v.value
}

func (v *NullableActionEmailDestination) Set(val *ActionEmailDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableActionEmailDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableActionEmailDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionEmailDestination(val *ActionEmailDestination) *NullableActionEmailDestination {
	return &NullableActionEmailDestination{value: val, isSet: true}
}

func (v NullableActionEmailDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionEmailDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


