/*
Metoro Alerts API

API for managing alerts in the Metoro observability platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the TimeseriesSpecifierFunctionsMathExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimeseriesSpecifierFunctionsMathExpression{}

// TimeseriesSpecifierFunctionsMathExpression Mathematical expression for custom functions
type TimeseriesSpecifierFunctionsMathExpression struct {
	// Array of variable names used in the expression
	Variables []string `json:"variables,omitempty"`
	// The mathematical expression to apply
	Expression *string `json:"expression,omitempty"`
}

// NewTimeseriesSpecifierFunctionsMathExpression instantiates a new TimeseriesSpecifierFunctionsMathExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeseriesSpecifierFunctionsMathExpression() *TimeseriesSpecifierFunctionsMathExpression {
	this := TimeseriesSpecifierFunctionsMathExpression{}
	return &this
}

// NewTimeseriesSpecifierFunctionsMathExpressionWithDefaults instantiates a new TimeseriesSpecifierFunctionsMathExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeseriesSpecifierFunctionsMathExpressionWithDefaults() *TimeseriesSpecifierFunctionsMathExpression {
	this := TimeseriesSpecifierFunctionsMathExpression{}
	return &this
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *TimeseriesSpecifierFunctionsMathExpression) GetVariables() []string {
	if o == nil || IsNil(o.Variables) {
		var ret []string
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeseriesSpecifierFunctionsMathExpression) GetVariablesOk() ([]string, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *TimeseriesSpecifierFunctionsMathExpression) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []string and assigns it to the Variables field.
func (o *TimeseriesSpecifierFunctionsMathExpression) SetVariables(v []string) {
	o.Variables = v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *TimeseriesSpecifierFunctionsMathExpression) GetExpression() string {
	if o == nil || IsNil(o.Expression) {
		var ret string
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeseriesSpecifierFunctionsMathExpression) GetExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *TimeseriesSpecifierFunctionsMathExpression) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given string and assigns it to the Expression field.
func (o *TimeseriesSpecifierFunctionsMathExpression) SetExpression(v string) {
	o.Expression = &v
}

func (o TimeseriesSpecifierFunctionsMathExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimeseriesSpecifierFunctionsMathExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	return toSerialize, nil
}

type NullableTimeseriesSpecifierFunctionsMathExpression struct {
	value *TimeseriesSpecifierFunctionsMathExpression
	isSet bool
}

func (v NullableTimeseriesSpecifierFunctionsMathExpression) Get() *TimeseriesSpecifierFunctionsMathExpression {
	return v.value
}

func (v *NullableTimeseriesSpecifierFunctionsMathExpression) Set(val *TimeseriesSpecifierFunctionsMathExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeseriesSpecifierFunctionsMathExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeseriesSpecifierFunctionsMathExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeseriesSpecifierFunctionsMathExpression(val *TimeseriesSpecifierFunctionsMathExpression) *NullableTimeseriesSpecifierFunctionsMathExpression {
	return &NullableTimeseriesSpecifierFunctionsMathExpression{value: val, isSet: true}
}

func (v NullableTimeseriesSpecifierFunctionsMathExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeseriesSpecifierFunctionsMathExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


