/*
Metoro Alerts API

API for managing alerts in the Metoro observability platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the ExpressionConfigFiltersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpressionConfigFiltersInner{}

// ExpressionConfigFiltersInner struct for ExpressionConfigFiltersInner
type ExpressionConfigFiltersInner struct {
	Key *string `json:"key,omitempty"`
	Value []string `json:"value,omitempty"`
	Operator *string `json:"operator,omitempty"`
}

// NewExpressionConfigFiltersInner instantiates a new ExpressionConfigFiltersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpressionConfigFiltersInner() *ExpressionConfigFiltersInner {
	this := ExpressionConfigFiltersInner{}
	return &this
}

// NewExpressionConfigFiltersInnerWithDefaults instantiates a new ExpressionConfigFiltersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpressionConfigFiltersInnerWithDefaults() *ExpressionConfigFiltersInner {
	this := ExpressionConfigFiltersInner{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ExpressionConfigFiltersInner) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionConfigFiltersInner) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ExpressionConfigFiltersInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ExpressionConfigFiltersInner) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ExpressionConfigFiltersInner) GetValue() []string {
	if o == nil || IsNil(o.Value) {
		var ret []string
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionConfigFiltersInner) GetValueOk() ([]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ExpressionConfigFiltersInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []string and assigns it to the Value field.
func (o *ExpressionConfigFiltersInner) SetValue(v []string) {
	o.Value = v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *ExpressionConfigFiltersInner) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionConfigFiltersInner) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *ExpressionConfigFiltersInner) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *ExpressionConfigFiltersInner) SetOperator(v string) {
	o.Operator = &v
}

func (o ExpressionConfigFiltersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpressionConfigFiltersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	return toSerialize, nil
}

type NullableExpressionConfigFiltersInner struct {
	value *ExpressionConfigFiltersInner
	isSet bool
}

func (v NullableExpressionConfigFiltersInner) Get() *ExpressionConfigFiltersInner {
	return v.value
}

func (v *NullableExpressionConfigFiltersInner) Set(val *ExpressionConfigFiltersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableExpressionConfigFiltersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableExpressionConfigFiltersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpressionConfigFiltersInner(val *ExpressionConfigFiltersInner) *NullableExpressionConfigFiltersInner {
	return &NullableExpressionConfigFiltersInner{value: val, isSet: true}
}

func (v NullableExpressionConfigFiltersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpressionConfigFiltersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


