# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from the latest golang base image for building
FROM golang:1.18-alpine AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o metoro-mcp-server .

# Start a new stage from scratch for the final build
FROM alpine:latest  

WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/metoro-mcp-server .

# Command to run the executable
CMD ["./metoro-mcp-server"]
