/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateUpdateDashboardRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUpdateDashboardRequest{}

// CreateUpdateDashboardRequest Request to create or update a dashboard
type CreateUpdateDashboardRequest struct {
	Dashboard Dashboard `json:"dashboard"`
}

type _CreateUpdateDashboardRequest CreateUpdateDashboardRequest

// NewCreateUpdateDashboardRequest instantiates a new CreateUpdateDashboardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUpdateDashboardRequest(dashboard Dashboard) *CreateUpdateDashboardRequest {
	this := CreateUpdateDashboardRequest{}
	this.Dashboard = dashboard
	return &this
}

// NewCreateUpdateDashboardRequestWithDefaults instantiates a new CreateUpdateDashboardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUpdateDashboardRequestWithDefaults() *CreateUpdateDashboardRequest {
	this := CreateUpdateDashboardRequest{}
	return &this
}

// GetDashboard returns the Dashboard field value
func (o *CreateUpdateDashboardRequest) GetDashboard() Dashboard {
	if o == nil {
		var ret Dashboard
		return ret
	}

	return o.Dashboard
}

// GetDashboardOk returns a tuple with the Dashboard field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateDashboardRequest) GetDashboardOk() (*Dashboard, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dashboard, true
}

// SetDashboard sets field value
func (o *CreateUpdateDashboardRequest) SetDashboard(v Dashboard) {
	o.Dashboard = v
}

func (o CreateUpdateDashboardRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUpdateDashboardRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dashboard"] = o.Dashboard
	return toSerialize, nil
}

func (o *CreateUpdateDashboardRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dashboard",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUpdateDashboardRequest := _CreateUpdateDashboardRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUpdateDashboardRequest)

	if err != nil {
		return err
	}

	*o = CreateUpdateDashboardRequest(varCreateUpdateDashboardRequest)

	return err
}

type NullableCreateUpdateDashboardRequest struct {
	value *CreateUpdateDashboardRequest
	isSet bool
}

func (v NullableCreateUpdateDashboardRequest) Get() *CreateUpdateDashboardRequest {
	return v.value
}

func (v *NullableCreateUpdateDashboardRequest) Set(val *CreateUpdateDashboardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUpdateDashboardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUpdateDashboardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUpdateDashboardRequest(val *CreateUpdateDashboardRequest) *NullableCreateUpdateDashboardRequest {
	return &NullableCreateUpdateDashboardRequest{value: val, isSet: true}
}

func (v NullableCreateUpdateDashboardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUpdateDashboardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
