/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the TraceWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TraceWidget{}

// TraceWidget Widget for displaying trace data
type TraceWidget struct {
	// Trace widget title
	Title           *string                     `json:"title,omitempty"`
	Expression      *TraceWidgetExpression      `json:"expression,omitempty"`
	DisplaySettings *TraceWidgetDisplaySettings `json:"displaySettings,omitempty"`
}

// NewTraceWidget instantiates a new TraceWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraceWidget() *TraceWidget {
	this := TraceWidget{}
	return &this
}

// NewTraceWidgetWithDefaults instantiates a new TraceWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTraceWidgetWithDefaults() *TraceWidget {
	this := TraceWidget{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *TraceWidget) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceWidget) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *TraceWidget) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *TraceWidget) SetTitle(v string) {
	o.Title = &v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *TraceWidget) GetExpression() TraceWidgetExpression {
	if o == nil || IsNil(o.Expression) {
		var ret TraceWidgetExpression
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceWidget) GetExpressionOk() (*TraceWidgetExpression, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *TraceWidget) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given TraceWidgetExpression and assigns it to the Expression field.
func (o *TraceWidget) SetExpression(v TraceWidgetExpression) {
	o.Expression = &v
}

// GetDisplaySettings returns the DisplaySettings field value if set, zero value otherwise.
func (o *TraceWidget) GetDisplaySettings() TraceWidgetDisplaySettings {
	if o == nil || IsNil(o.DisplaySettings) {
		var ret TraceWidgetDisplaySettings
		return ret
	}
	return *o.DisplaySettings
}

// GetDisplaySettingsOk returns a tuple with the DisplaySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceWidget) GetDisplaySettingsOk() (*TraceWidgetDisplaySettings, bool) {
	if o == nil || IsNil(o.DisplaySettings) {
		return nil, false
	}
	return o.DisplaySettings, true
}

// HasDisplaySettings returns a boolean if a field has been set.
func (o *TraceWidget) HasDisplaySettings() bool {
	if o != nil && !IsNil(o.DisplaySettings) {
		return true
	}

	return false
}

// SetDisplaySettings gets a reference to the given TraceWidgetDisplaySettings and assigns it to the DisplaySettings field.
func (o *TraceWidget) SetDisplaySettings(v TraceWidgetDisplaySettings) {
	o.DisplaySettings = &v
}

func (o TraceWidget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TraceWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.DisplaySettings) {
		toSerialize["displaySettings"] = o.DisplaySettings
	}
	return toSerialize, nil
}

type NullableTraceWidget struct {
	value *TraceWidget
	isSet bool
}

func (v NullableTraceWidget) Get() *TraceWidget {
	return v.value
}

func (v *NullableTraceWidget) Set(val *TraceWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableTraceWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableTraceWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraceWidget(val *TraceWidget) *NullableTraceWidget {
	return &NullableTraceWidget{value: val, isSet: true}
}

func (v NullableTraceWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraceWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
