/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the LogWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogWidget{}

// LogWidget Widget for displaying log data
type LogWidget struct {
	// Log widget title
	Title           *string                   `json:"title,omitempty"`
	Expression      *LogWidgetExpression      `json:"expression,omitempty"`
	DisplaySettings *LogWidgetDisplaySettings `json:"displaySettings,omitempty"`
}

// NewLogWidget instantiates a new LogWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogWidget() *LogWidget {
	this := LogWidget{}
	return &this
}

// NewLogWidgetWithDefaults instantiates a new LogWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogWidgetWithDefaults() *LogWidget {
	this := LogWidget{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *LogWidget) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogWidget) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *LogWidget) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *LogWidget) SetTitle(v string) {
	o.Title = &v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *LogWidget) GetExpression() LogWidgetExpression {
	if o == nil || IsNil(o.Expression) {
		var ret LogWidgetExpression
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogWidget) GetExpressionOk() (*LogWidgetExpression, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *LogWidget) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given LogWidgetExpression and assigns it to the Expression field.
func (o *LogWidget) SetExpression(v LogWidgetExpression) {
	o.Expression = &v
}

// GetDisplaySettings returns the DisplaySettings field value if set, zero value otherwise.
func (o *LogWidget) GetDisplaySettings() LogWidgetDisplaySettings {
	if o == nil || IsNil(o.DisplaySettings) {
		var ret LogWidgetDisplaySettings
		return ret
	}
	return *o.DisplaySettings
}

// GetDisplaySettingsOk returns a tuple with the DisplaySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogWidget) GetDisplaySettingsOk() (*LogWidgetDisplaySettings, bool) {
	if o == nil || IsNil(o.DisplaySettings) {
		return nil, false
	}
	return o.DisplaySettings, true
}

// HasDisplaySettings returns a boolean if a field has been set.
func (o *LogWidget) HasDisplaySettings() bool {
	if o != nil && !IsNil(o.DisplaySettings) {
		return true
	}

	return false
}

// SetDisplaySettings gets a reference to the given LogWidgetDisplaySettings and assigns it to the DisplaySettings field.
func (o *LogWidget) SetDisplaySettings(v LogWidgetDisplaySettings) {
	o.DisplaySettings = &v
}

func (o LogWidget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.DisplaySettings) {
		toSerialize["displaySettings"] = o.DisplaySettings
	}
	return toSerialize, nil
}

type NullableLogWidget struct {
	value *LogWidget
	isSet bool
}

func (v NullableLogWidget) Get() *LogWidget {
	return v.value
}

func (v *NullableLogWidget) Set(val *LogWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableLogWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableLogWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogWidget(val *LogWidget) *NullableLogWidget {
	return &NullableLogWidget{value: val, isSet: true}
}

func (v NullableLogWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
