/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Variable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Variable{}

// Variable Dashboard variable for dynamic content
type Variable struct {
	// Whether this variable can be overridden
	Overridable *bool `json:"overridable,omitempty"`
	// Default value for this variable
	DefaultValue *string `json:"defaultValue,omitempty"`
	// Name of the variable
	Name     string            `json:"name"`
	Selector *VariableSelector `json:"selector,omitempty"`
}

type _Variable Variable

// NewVariable instantiates a new Variable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariable(name string) *Variable {
	this := Variable{}
	var overridable bool = true
	this.Overridable = &overridable
	this.Name = name
	return &this
}

// NewVariableWithDefaults instantiates a new Variable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableWithDefaults() *Variable {
	this := Variable{}
	var overridable bool = true
	this.Overridable = &overridable
	return &this
}

// GetOverridable returns the Overridable field value if set, zero value otherwise.
func (o *Variable) GetOverridable() bool {
	if o == nil || IsNil(o.Overridable) {
		var ret bool
		return ret
	}
	return *o.Overridable
}

// GetOverridableOk returns a tuple with the Overridable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Variable) GetOverridableOk() (*bool, bool) {
	if o == nil || IsNil(o.Overridable) {
		return nil, false
	}
	return o.Overridable, true
}

// HasOverridable returns a boolean if a field has been set.
func (o *Variable) HasOverridable() bool {
	if o != nil && !IsNil(o.Overridable) {
		return true
	}

	return false
}

// SetOverridable gets a reference to the given bool and assigns it to the Overridable field.
func (o *Variable) SetOverridable(v bool) {
	o.Overridable = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *Variable) GetDefaultValue() string {
	if o == nil || IsNil(o.DefaultValue) {
		var ret string
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Variable) GetDefaultValueOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *Variable) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given string and assigns it to the DefaultValue field.
func (o *Variable) SetDefaultValue(v string) {
	o.DefaultValue = &v
}

// GetName returns the Name field value
func (o *Variable) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Variable) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Variable) SetName(v string) {
	o.Name = v
}

// GetSelector returns the Selector field value if set, zero value otherwise.
func (o *Variable) GetSelector() VariableSelector {
	if o == nil || IsNil(o.Selector) {
		var ret VariableSelector
		return ret
	}
	return *o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Variable) GetSelectorOk() (*VariableSelector, bool) {
	if o == nil || IsNil(o.Selector) {
		return nil, false
	}
	return o.Selector, true
}

// HasSelector returns a boolean if a field has been set.
func (o *Variable) HasSelector() bool {
	if o != nil && !IsNil(o.Selector) {
		return true
	}

	return false
}

// SetSelector gets a reference to the given VariableSelector and assigns it to the Selector field.
func (o *Variable) SetSelector(v VariableSelector) {
	o.Selector = &v
}

func (o Variable) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Variable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Overridable) {
		toSerialize["overridable"] = o.Overridable
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Selector) {
		toSerialize["selector"] = o.Selector
	}
	return toSerialize, nil
}

func (o *Variable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVariable := _Variable{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVariable)

	if err != nil {
		return err
	}

	*o = Variable(varVariable)

	return err
}

type NullableVariable struct {
	value *Variable
	isSet bool
}

func (v NullableVariable) Get() *Variable {
	return v.value
}

func (v *NullableVariable) Set(val *Variable) {
	v.value = val
	v.isSet = true
}

func (v NullableVariable) IsSet() bool {
	return v.isSet
}

func (v *NullableVariable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariable(val *Variable) *NullableVariable {
	return &NullableVariable{value: val, isSet: true}
}

func (v NullableVariable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
