/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateUpdateDashboardResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUpdateDashboardResponse{}

// CreateUpdateDashboardResponse Response from creating or updating a dashboard
type CreateUpdateDashboardResponse struct {
	// Unique identifier of the created/updated dashboard
	Id string `json:"id"`
}

type _CreateUpdateDashboardResponse CreateUpdateDashboardResponse

// NewCreateUpdateDashboardResponse instantiates a new CreateUpdateDashboardResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUpdateDashboardResponse(id string) *CreateUpdateDashboardResponse {
	this := CreateUpdateDashboardResponse{}
	this.Id = id
	return &this
}

// NewCreateUpdateDashboardResponseWithDefaults instantiates a new CreateUpdateDashboardResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUpdateDashboardResponseWithDefaults() *CreateUpdateDashboardResponse {
	this := CreateUpdateDashboardResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateUpdateDashboardResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateDashboardResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateUpdateDashboardResponse) SetId(v string) {
	o.Id = v
}

func (o CreateUpdateDashboardResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUpdateDashboardResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CreateUpdateDashboardResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUpdateDashboardResponse := _CreateUpdateDashboardResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUpdateDashboardResponse)

	if err != nil {
		return err
	}

	*o = CreateUpdateDashboardResponse(varCreateUpdateDashboardResponse)

	return err
}

type NullableCreateUpdateDashboardResponse struct {
	value *CreateUpdateDashboardResponse
	isSet bool
}

func (v NullableCreateUpdateDashboardResponse) Get() *CreateUpdateDashboardResponse {
	return v.value
}

func (v *NullableCreateUpdateDashboardResponse) Set(val *CreateUpdateDashboardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUpdateDashboardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUpdateDashboardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUpdateDashboardResponse(val *CreateUpdateDashboardResponse) *NullableCreateUpdateDashboardResponse {
	return &NullableCreateUpdateDashboardResponse{value: val, isSet: true}
}

func (v NullableCreateUpdateDashboardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUpdateDashboardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
