/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the TraceWidgetDisplaySettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TraceWidgetDisplaySettings{}

// TraceWidgetDisplaySettings Display settings for trace widget
type TraceWidgetDisplaySettings struct {
	// Whether to hide the search bar
	HideSearchBar *bool `json:"hideSearchBar,omitempty"`
	// Array of column names to display
	Columns []string `json:"columns,omitempty"`
}

// NewTraceWidgetDisplaySettings instantiates a new TraceWidgetDisplaySettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraceWidgetDisplaySettings() *TraceWidgetDisplaySettings {
	this := TraceWidgetDisplaySettings{}
	return &this
}

// NewTraceWidgetDisplaySettingsWithDefaults instantiates a new TraceWidgetDisplaySettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTraceWidgetDisplaySettingsWithDefaults() *TraceWidgetDisplaySettings {
	this := TraceWidgetDisplaySettings{}
	return &this
}

// GetHideSearchBar returns the HideSearchBar field value if set, zero value otherwise.
func (o *TraceWidgetDisplaySettings) GetHideSearchBar() bool {
	if o == nil || IsNil(o.HideSearchBar) {
		var ret bool
		return ret
	}
	return *o.HideSearchBar
}

// GetHideSearchBarOk returns a tuple with the HideSearchBar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceWidgetDisplaySettings) GetHideSearchBarOk() (*bool, bool) {
	if o == nil || IsNil(o.HideSearchBar) {
		return nil, false
	}
	return o.HideSearchBar, true
}

// HasHideSearchBar returns a boolean if a field has been set.
func (o *TraceWidgetDisplaySettings) HasHideSearchBar() bool {
	if o != nil && !IsNil(o.HideSearchBar) {
		return true
	}

	return false
}

// SetHideSearchBar gets a reference to the given bool and assigns it to the HideSearchBar field.
func (o *TraceWidgetDisplaySettings) SetHideSearchBar(v bool) {
	o.HideSearchBar = &v
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *TraceWidgetDisplaySettings) GetColumns() []string {
	if o == nil || IsNil(o.Columns) {
		var ret []string
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceWidgetDisplaySettings) GetColumnsOk() ([]string, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *TraceWidgetDisplaySettings) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []string and assigns it to the Columns field.
func (o *TraceWidgetDisplaySettings) SetColumns(v []string) {
	o.Columns = v
}

func (o TraceWidgetDisplaySettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TraceWidgetDisplaySettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HideSearchBar) {
		toSerialize["hideSearchBar"] = o.HideSearchBar
	}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	return toSerialize, nil
}

type NullableTraceWidgetDisplaySettings struct {
	value *TraceWidgetDisplaySettings
	isSet bool
}

func (v NullableTraceWidgetDisplaySettings) Get() *TraceWidgetDisplaySettings {
	return v.value
}

func (v *NullableTraceWidgetDisplaySettings) Set(val *TraceWidgetDisplaySettings) {
	v.value = val
	v.isSet = true
}

func (v NullableTraceWidgetDisplaySettings) IsSet() bool {
	return v.isSet
}

func (v *NullableTraceWidgetDisplaySettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraceWidgetDisplaySettings(val *TraceWidgetDisplaySettings) *NullableTraceWidgetDisplaySettings {
	return &NullableTraceWidgetDisplaySettings{value: val, isSet: true}
}

func (v NullableTraceWidgetDisplaySettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraceWidgetDisplaySettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
