/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Widget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Widget{}

// Widget Dashboard widget
type Widget struct {
	// Type of widget
	Type     string          `json:"type"`
	Position *Position       `json:"position,omitempty"`
	Group    *GroupWidget    `json:"group,omitempty"`
	Markdown *MarkdownWidget `json:"markdown,omitempty"`
	Chart    *ChartWidget    `json:"chart,omitempty"`
	Stat     *StatWidget     `json:"stat,omitempty"`
	Gauge    *GaugeWidget    `json:"gauge,omitempty"`
	Trace    *TraceWidget    `json:"trace,omitempty"`
	Log      *LogWidget      `json:"log,omitempty"`
}

type _Widget Widget

// NewWidget instantiates a new Widget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWidget(type_ string) *Widget {
	this := Widget{}
	this.Type = type_
	return &this
}

// NewWidgetWithDefaults instantiates a new Widget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWidgetWithDefaults() *Widget {
	this := Widget{}
	return &this
}

// GetType returns the Type field value
func (o *Widget) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Widget) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Widget) SetType(v string) {
	o.Type = v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *Widget) GetPosition() Position {
	if o == nil || IsNil(o.Position) {
		var ret Position
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Widget) GetPositionOk() (*Position, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *Widget) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given Position and assigns it to the Position field.
func (o *Widget) SetPosition(v Position) {
	o.Position = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *Widget) GetGroup() GroupWidget {
	if o == nil || IsNil(o.Group) {
		var ret GroupWidget
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Widget) GetGroupOk() (*GroupWidget, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *Widget) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given GroupWidget and assigns it to the Group field.
func (o *Widget) SetGroup(v GroupWidget) {
	o.Group = &v
}

// GetMarkdown returns the Markdown field value if set, zero value otherwise.
func (o *Widget) GetMarkdown() MarkdownWidget {
	if o == nil || IsNil(o.Markdown) {
		var ret MarkdownWidget
		return ret
	}
	return *o.Markdown
}

// GetMarkdownOk returns a tuple with the Markdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Widget) GetMarkdownOk() (*MarkdownWidget, bool) {
	if o == nil || IsNil(o.Markdown) {
		return nil, false
	}
	return o.Markdown, true
}

// HasMarkdown returns a boolean if a field has been set.
func (o *Widget) HasMarkdown() bool {
	if o != nil && !IsNil(o.Markdown) {
		return true
	}

	return false
}

// SetMarkdown gets a reference to the given MarkdownWidget and assigns it to the Markdown field.
func (o *Widget) SetMarkdown(v MarkdownWidget) {
	o.Markdown = &v
}

// GetChart returns the Chart field value if set, zero value otherwise.
func (o *Widget) GetChart() ChartWidget {
	if o == nil || IsNil(o.Chart) {
		var ret ChartWidget
		return ret
	}
	return *o.Chart
}

// GetChartOk returns a tuple with the Chart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Widget) GetChartOk() (*ChartWidget, bool) {
	if o == nil || IsNil(o.Chart) {
		return nil, false
	}
	return o.Chart, true
}

// HasChart returns a boolean if a field has been set.
func (o *Widget) HasChart() bool {
	if o != nil && !IsNil(o.Chart) {
		return true
	}

	return false
}

// SetChart gets a reference to the given ChartWidget and assigns it to the Chart field.
func (o *Widget) SetChart(v ChartWidget) {
	o.Chart = &v
}

// GetStat returns the Stat field value if set, zero value otherwise.
func (o *Widget) GetStat() StatWidget {
	if o == nil || IsNil(o.Stat) {
		var ret StatWidget
		return ret
	}
	return *o.Stat
}

// GetStatOk returns a tuple with the Stat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Widget) GetStatOk() (*StatWidget, bool) {
	if o == nil || IsNil(o.Stat) {
		return nil, false
	}
	return o.Stat, true
}

// HasStat returns a boolean if a field has been set.
func (o *Widget) HasStat() bool {
	if o != nil && !IsNil(o.Stat) {
		return true
	}

	return false
}

// SetStat gets a reference to the given StatWidget and assigns it to the Stat field.
func (o *Widget) SetStat(v StatWidget) {
	o.Stat = &v
}

// GetGauge returns the Gauge field value if set, zero value otherwise.
func (o *Widget) GetGauge() GaugeWidget {
	if o == nil || IsNil(o.Gauge) {
		var ret GaugeWidget
		return ret
	}
	return *o.Gauge
}

// GetGaugeOk returns a tuple with the Gauge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Widget) GetGaugeOk() (*GaugeWidget, bool) {
	if o == nil || IsNil(o.Gauge) {
		return nil, false
	}
	return o.Gauge, true
}

// HasGauge returns a boolean if a field has been set.
func (o *Widget) HasGauge() bool {
	if o != nil && !IsNil(o.Gauge) {
		return true
	}

	return false
}

// SetGauge gets a reference to the given GaugeWidget and assigns it to the Gauge field.
func (o *Widget) SetGauge(v GaugeWidget) {
	o.Gauge = &v
}

// GetTrace returns the Trace field value if set, zero value otherwise.
func (o *Widget) GetTrace() TraceWidget {
	if o == nil || IsNil(o.Trace) {
		var ret TraceWidget
		return ret
	}
	return *o.Trace
}

// GetTraceOk returns a tuple with the Trace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Widget) GetTraceOk() (*TraceWidget, bool) {
	if o == nil || IsNil(o.Trace) {
		return nil, false
	}
	return o.Trace, true
}

// HasTrace returns a boolean if a field has been set.
func (o *Widget) HasTrace() bool {
	if o != nil && !IsNil(o.Trace) {
		return true
	}

	return false
}

// SetTrace gets a reference to the given TraceWidget and assigns it to the Trace field.
func (o *Widget) SetTrace(v TraceWidget) {
	o.Trace = &v
}

// GetLog returns the Log field value if set, zero value otherwise.
func (o *Widget) GetLog() LogWidget {
	if o == nil || IsNil(o.Log) {
		var ret LogWidget
		return ret
	}
	return *o.Log
}

// GetLogOk returns a tuple with the Log field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Widget) GetLogOk() (*LogWidget, bool) {
	if o == nil || IsNil(o.Log) {
		return nil, false
	}
	return o.Log, true
}

// HasLog returns a boolean if a field has been set.
func (o *Widget) HasLog() bool {
	if o != nil && !IsNil(o.Log) {
		return true
	}

	return false
}

// SetLog gets a reference to the given LogWidget and assigns it to the Log field.
func (o *Widget) SetLog(v LogWidget) {
	o.Log = &v
}

func (o Widget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Widget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Markdown) {
		toSerialize["markdown"] = o.Markdown
	}
	if !IsNil(o.Chart) {
		toSerialize["chart"] = o.Chart
	}
	if !IsNil(o.Stat) {
		toSerialize["stat"] = o.Stat
	}
	if !IsNil(o.Gauge) {
		toSerialize["gauge"] = o.Gauge
	}
	if !IsNil(o.Trace) {
		toSerialize["trace"] = o.Trace
	}
	if !IsNil(o.Log) {
		toSerialize["log"] = o.Log
	}
	return toSerialize, nil
}

func (o *Widget) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWidget := _Widget{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWidget)

	if err != nil {
		return err
	}

	*o = Widget(varWidget)

	return err
}

type NullableWidget struct {
	value *Widget
	isSet bool
}

func (v NullableWidget) Get() *Widget {
	return v.value
}

func (v *NullableWidget) Set(val *Widget) {
	v.value = val
	v.isSet = true
}

func (v NullableWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWidget(val *Widget) *NullableWidget {
	return &NullableWidget{value: val, isSet: true}
}

func (v NullableWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
