/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MetoroQLQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetoroQLQuery{}

// MetoroQLQuery Query configuration for MetoroQL
type MetoroQLQuery struct {
	// MetoroQL query string
	Query string `json:"query"`
	// Size of the time buckets in seconds (0 for auto)
	BucketSize      *int64                `json:"bucketSize,omitempty"`
	DisplaySettings *ChartDisplaySettings `json:"displaySettings,omitempty"`
}

type _MetoroQLQuery MetoroQLQuery

// NewMetoroQLQuery instantiates a new MetoroQLQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetoroQLQuery(query string) *MetoroQLQuery {
	this := MetoroQLQuery{}
	this.Query = query
	var bucketSize int64 = 0
	this.BucketSize = &bucketSize
	return &this
}

// NewMetoroQLQueryWithDefaults instantiates a new MetoroQLQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetoroQLQueryWithDefaults() *MetoroQLQuery {
	this := MetoroQLQuery{}
	var bucketSize int64 = 0
	this.BucketSize = &bucketSize
	return &this
}

// GetQuery returns the Query field value
func (o *MetoroQLQuery) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *MetoroQLQuery) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *MetoroQLQuery) SetQuery(v string) {
	o.Query = v
}

// GetBucketSize returns the BucketSize field value if set, zero value otherwise.
func (o *MetoroQLQuery) GetBucketSize() int64 {
	if o == nil || IsNil(o.BucketSize) {
		var ret int64
		return ret
	}
	return *o.BucketSize
}

// GetBucketSizeOk returns a tuple with the BucketSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetoroQLQuery) GetBucketSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.BucketSize) {
		return nil, false
	}
	return o.BucketSize, true
}

// HasBucketSize returns a boolean if a field has been set.
func (o *MetoroQLQuery) HasBucketSize() bool {
	if o != nil && !IsNil(o.BucketSize) {
		return true
	}

	return false
}

// SetBucketSize gets a reference to the given int64 and assigns it to the BucketSize field.
func (o *MetoroQLQuery) SetBucketSize(v int64) {
	o.BucketSize = &v
}

// GetDisplaySettings returns the DisplaySettings field value if set, zero value otherwise.
func (o *MetoroQLQuery) GetDisplaySettings() ChartDisplaySettings {
	if o == nil || IsNil(o.DisplaySettings) {
		var ret ChartDisplaySettings
		return ret
	}
	return *o.DisplaySettings
}

// GetDisplaySettingsOk returns a tuple with the DisplaySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetoroQLQuery) GetDisplaySettingsOk() (*ChartDisplaySettings, bool) {
	if o == nil || IsNil(o.DisplaySettings) {
		return nil, false
	}
	return o.DisplaySettings, true
}

// HasDisplaySettings returns a boolean if a field has been set.
func (o *MetoroQLQuery) HasDisplaySettings() bool {
	if o != nil && !IsNil(o.DisplaySettings) {
		return true
	}

	return false
}

// SetDisplaySettings gets a reference to the given ChartDisplaySettings and assigns it to the DisplaySettings field.
func (o *MetoroQLQuery) SetDisplaySettings(v ChartDisplaySettings) {
	o.DisplaySettings = &v
}

func (o MetoroQLQuery) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetoroQLQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.BucketSize) {
		toSerialize["bucketSize"] = o.BucketSize
	}
	if !IsNil(o.DisplaySettings) {
		toSerialize["displaySettings"] = o.DisplaySettings
	}
	return toSerialize, nil
}

func (o *MetoroQLQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetoroQLQuery := _MetoroQLQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetoroQLQuery)

	if err != nil {
		return err
	}

	*o = MetoroQLQuery(varMetoroQLQuery)

	return err
}

type NullableMetoroQLQuery struct {
	value *MetoroQLQuery
	isSet bool
}

func (v NullableMetoroQLQuery) Get() *MetoroQLQuery {
	return v.value
}

func (v *NullableMetoroQLQuery) Set(val *MetoroQLQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableMetoroQLQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableMetoroQLQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetoroQLQuery(val *MetoroQLQuery) *NullableMetoroQLQuery {
	return &NullableMetoroQLQuery{value: val, isSet: true}
}

func (v NullableMetoroQLQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetoroQLQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
