/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ChartWidgetDisplaySettingsThresholdsStepsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartWidgetDisplaySettingsThresholdsStepsInner{}

// ChartWidgetDisplaySettingsThresholdsStepsInner struct for ChartWidgetDisplaySettingsThresholdsStepsInner
type ChartWidgetDisplaySettingsThresholdsStepsInner struct {
	// Threshold value
	Value float64 `json:"value"`
	// Color in hex format for this threshold level
	Color *string `json:"color,omitempty"`
	// Name for this threshold level
	Name *string `json:"name,omitempty"`
}

type _ChartWidgetDisplaySettingsThresholdsStepsInner ChartWidgetDisplaySettingsThresholdsStepsInner

// NewChartWidgetDisplaySettingsThresholdsStepsInner instantiates a new ChartWidgetDisplaySettingsThresholdsStepsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartWidgetDisplaySettingsThresholdsStepsInner(value float64) *ChartWidgetDisplaySettingsThresholdsStepsInner {
	this := ChartWidgetDisplaySettingsThresholdsStepsInner{}
	this.Value = value
	return &this
}

// NewChartWidgetDisplaySettingsThresholdsStepsInnerWithDefaults instantiates a new ChartWidgetDisplaySettingsThresholdsStepsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartWidgetDisplaySettingsThresholdsStepsInnerWithDefaults() *ChartWidgetDisplaySettingsThresholdsStepsInner {
	this := ChartWidgetDisplaySettingsThresholdsStepsInner{}
	return &this
}

// GetValue returns the Value field value
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) SetValue(v float64) {
	o.Value = v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) SetColor(v string) {
	o.Color = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) SetName(v string) {
	o.Name = &v
}

func (o ChartWidgetDisplaySettingsThresholdsStepsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartWidgetDisplaySettingsThresholdsStepsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

func (o *ChartWidgetDisplaySettingsThresholdsStepsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChartWidgetDisplaySettingsThresholdsStepsInner := _ChartWidgetDisplaySettingsThresholdsStepsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChartWidgetDisplaySettingsThresholdsStepsInner)

	if err != nil {
		return err
	}

	*o = ChartWidgetDisplaySettingsThresholdsStepsInner(varChartWidgetDisplaySettingsThresholdsStepsInner)

	return err
}

type NullableChartWidgetDisplaySettingsThresholdsStepsInner struct {
	value *ChartWidgetDisplaySettingsThresholdsStepsInner
	isSet bool
}

func (v NullableChartWidgetDisplaySettingsThresholdsStepsInner) Get() *ChartWidgetDisplaySettingsThresholdsStepsInner {
	return v.value
}

func (v *NullableChartWidgetDisplaySettingsThresholdsStepsInner) Set(val *ChartWidgetDisplaySettingsThresholdsStepsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableChartWidgetDisplaySettingsThresholdsStepsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableChartWidgetDisplaySettingsThresholdsStepsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartWidgetDisplaySettingsThresholdsStepsInner(val *ChartWidgetDisplaySettingsThresholdsStepsInner) *NullableChartWidgetDisplaySettingsThresholdsStepsInner {
	return &NullableChartWidgetDisplaySettingsThresholdsStepsInner{value: val, isSet: true}
}

func (v NullableChartWidgetDisplaySettingsThresholdsStepsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartWidgetDisplaySettingsThresholdsStepsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
