/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the GaugeDisplaySettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GaugeDisplaySettings{}

// GaugeDisplaySettings Display settings for gauge widget
type GaugeDisplaySettings struct {
	GlobalSettings *GaugeGlobalSettings `json:"globalSettings,omitempty"`
}

// NewGaugeDisplaySettings instantiates a new GaugeDisplaySettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGaugeDisplaySettings() *GaugeDisplaySettings {
	this := GaugeDisplaySettings{}
	return &this
}

// NewGaugeDisplaySettingsWithDefaults instantiates a new GaugeDisplaySettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGaugeDisplaySettingsWithDefaults() *GaugeDisplaySettings {
	this := GaugeDisplaySettings{}
	return &this
}

// GetGlobalSettings returns the GlobalSettings field value if set, zero value otherwise.
func (o *GaugeDisplaySettings) GetGlobalSettings() GaugeGlobalSettings {
	if o == nil || IsNil(o.GlobalSettings) {
		var ret GaugeGlobalSettings
		return ret
	}
	return *o.GlobalSettings
}

// GetGlobalSettingsOk returns a tuple with the GlobalSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeDisplaySettings) GetGlobalSettingsOk() (*GaugeGlobalSettings, bool) {
	if o == nil || IsNil(o.GlobalSettings) {
		return nil, false
	}
	return o.GlobalSettings, true
}

// HasGlobalSettings returns a boolean if a field has been set.
func (o *GaugeDisplaySettings) HasGlobalSettings() bool {
	if o != nil && !IsNil(o.GlobalSettings) {
		return true
	}

	return false
}

// SetGlobalSettings gets a reference to the given GaugeGlobalSettings and assigns it to the GlobalSettings field.
func (o *GaugeDisplaySettings) SetGlobalSettings(v GaugeGlobalSettings) {
	o.GlobalSettings = &v
}

func (o GaugeDisplaySettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GaugeDisplaySettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GlobalSettings) {
		toSerialize["globalSettings"] = o.GlobalSettings
	}
	return toSerialize, nil
}

type NullableGaugeDisplaySettings struct {
	value *GaugeDisplaySettings
	isSet bool
}

func (v NullableGaugeDisplaySettings) Get() *GaugeDisplaySettings {
	return v.value
}

func (v *NullableGaugeDisplaySettings) Set(val *GaugeDisplaySettings) {
	v.value = val
	v.isSet = true
}

func (v NullableGaugeDisplaySettings) IsSet() bool {
	return v.isSet
}

func (v *NullableGaugeDisplaySettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGaugeDisplaySettings(val *GaugeDisplaySettings) *NullableGaugeDisplaySettings {
	return &NullableGaugeDisplaySettings{value: val, isSet: true}
}

func (v NullableGaugeDisplaySettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGaugeDisplaySettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
