/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the GaugeWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GaugeWidget{}

// GaugeWidget Widget for displaying gauge metrics
type GaugeWidget struct {
	// Gauge title
	Title           *string                `json:"title,omitempty"`
	Expression      *GaugeWidgetExpression `json:"expression,omitempty"`
	DisplaySettings *GaugeDisplaySettings  `json:"displaySettings,omitempty"`
}

// NewGaugeWidget instantiates a new GaugeWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGaugeWidget() *GaugeWidget {
	this := GaugeWidget{}
	return &this
}

// NewGaugeWidgetWithDefaults instantiates a new GaugeWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGaugeWidgetWithDefaults() *GaugeWidget {
	this := GaugeWidget{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GaugeWidget) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeWidget) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GaugeWidget) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GaugeWidget) SetTitle(v string) {
	o.Title = &v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *GaugeWidget) GetExpression() GaugeWidgetExpression {
	if o == nil || IsNil(o.Expression) {
		var ret GaugeWidgetExpression
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeWidget) GetExpressionOk() (*GaugeWidgetExpression, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *GaugeWidget) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given GaugeWidgetExpression and assigns it to the Expression field.
func (o *GaugeWidget) SetExpression(v GaugeWidgetExpression) {
	o.Expression = &v
}

// GetDisplaySettings returns the DisplaySettings field value if set, zero value otherwise.
func (o *GaugeWidget) GetDisplaySettings() GaugeDisplaySettings {
	if o == nil || IsNil(o.DisplaySettings) {
		var ret GaugeDisplaySettings
		return ret
	}
	return *o.DisplaySettings
}

// GetDisplaySettingsOk returns a tuple with the DisplaySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeWidget) GetDisplaySettingsOk() (*GaugeDisplaySettings, bool) {
	if o == nil || IsNil(o.DisplaySettings) {
		return nil, false
	}
	return o.DisplaySettings, true
}

// HasDisplaySettings returns a boolean if a field has been set.
func (o *GaugeWidget) HasDisplaySettings() bool {
	if o != nil && !IsNil(o.DisplaySettings) {
		return true
	}

	return false
}

// SetDisplaySettings gets a reference to the given GaugeDisplaySettings and assigns it to the DisplaySettings field.
func (o *GaugeWidget) SetDisplaySettings(v GaugeDisplaySettings) {
	o.DisplaySettings = &v
}

func (o GaugeWidget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GaugeWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.DisplaySettings) {
		toSerialize["displaySettings"] = o.DisplaySettings
	}
	return toSerialize, nil
}

type NullableGaugeWidget struct {
	value *GaugeWidget
	isSet bool
}

func (v NullableGaugeWidget) Get() *GaugeWidget {
	return v.value
}

func (v *NullableGaugeWidget) Set(val *GaugeWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableGaugeWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableGaugeWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGaugeWidget(val *GaugeWidget) *NullableGaugeWidget {
	return &NullableGaugeWidget{value: val, isSet: true}
}

func (v NullableGaugeWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGaugeWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
