/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the ChartDisplaySettingsLineSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartDisplaySettingsLineSettings{}

// ChartDisplaySettingsLineSettings Settings for line display
type ChartDisplaySettingsLineSettings struct {
	// Type of line
	LineType *string `json:"lineType,omitempty"`
	// Color of the line
	LineColour *string `json:"lineColour,omitempty"`
	// Color of dots on the line
	LineDotColor *string `json:"lineDotColor,omitempty"`
	// Size of dots on the line (0 for no dots)
	LineDotSize *int64 `json:"lineDotSize,omitempty"`
}

// NewChartDisplaySettingsLineSettings instantiates a new ChartDisplaySettingsLineSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartDisplaySettingsLineSettings() *ChartDisplaySettingsLineSettings {
	this := ChartDisplaySettingsLineSettings{}
	var lineType string = "solid"
	this.LineType = &lineType
	var lineDotSize int64 = 0
	this.LineDotSize = &lineDotSize
	return &this
}

// NewChartDisplaySettingsLineSettingsWithDefaults instantiates a new ChartDisplaySettingsLineSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartDisplaySettingsLineSettingsWithDefaults() *ChartDisplaySettingsLineSettings {
	this := ChartDisplaySettingsLineSettings{}
	var lineType string = "solid"
	this.LineType = &lineType
	var lineDotSize int64 = 0
	this.LineDotSize = &lineDotSize
	return &this
}

// GetLineType returns the LineType field value if set, zero value otherwise.
func (o *ChartDisplaySettingsLineSettings) GetLineType() string {
	if o == nil || IsNil(o.LineType) {
		var ret string
		return ret
	}
	return *o.LineType
}

// GetLineTypeOk returns a tuple with the LineType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartDisplaySettingsLineSettings) GetLineTypeOk() (*string, bool) {
	if o == nil || IsNil(o.LineType) {
		return nil, false
	}
	return o.LineType, true
}

// HasLineType returns a boolean if a field has been set.
func (o *ChartDisplaySettingsLineSettings) HasLineType() bool {
	if o != nil && !IsNil(o.LineType) {
		return true
	}

	return false
}

// SetLineType gets a reference to the given string and assigns it to the LineType field.
func (o *ChartDisplaySettingsLineSettings) SetLineType(v string) {
	o.LineType = &v
}

// GetLineColour returns the LineColour field value if set, zero value otherwise.
func (o *ChartDisplaySettingsLineSettings) GetLineColour() string {
	if o == nil || IsNil(o.LineColour) {
		var ret string
		return ret
	}
	return *o.LineColour
}

// GetLineColourOk returns a tuple with the LineColour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartDisplaySettingsLineSettings) GetLineColourOk() (*string, bool) {
	if o == nil || IsNil(o.LineColour) {
		return nil, false
	}
	return o.LineColour, true
}

// HasLineColour returns a boolean if a field has been set.
func (o *ChartDisplaySettingsLineSettings) HasLineColour() bool {
	if o != nil && !IsNil(o.LineColour) {
		return true
	}

	return false
}

// SetLineColour gets a reference to the given string and assigns it to the LineColour field.
func (o *ChartDisplaySettingsLineSettings) SetLineColour(v string) {
	o.LineColour = &v
}

// GetLineDotColor returns the LineDotColor field value if set, zero value otherwise.
func (o *ChartDisplaySettingsLineSettings) GetLineDotColor() string {
	if o == nil || IsNil(o.LineDotColor) {
		var ret string
		return ret
	}
	return *o.LineDotColor
}

// GetLineDotColorOk returns a tuple with the LineDotColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartDisplaySettingsLineSettings) GetLineDotColorOk() (*string, bool) {
	if o == nil || IsNil(o.LineDotColor) {
		return nil, false
	}
	return o.LineDotColor, true
}

// HasLineDotColor returns a boolean if a field has been set.
func (o *ChartDisplaySettingsLineSettings) HasLineDotColor() bool {
	if o != nil && !IsNil(o.LineDotColor) {
		return true
	}

	return false
}

// SetLineDotColor gets a reference to the given string and assigns it to the LineDotColor field.
func (o *ChartDisplaySettingsLineSettings) SetLineDotColor(v string) {
	o.LineDotColor = &v
}

// GetLineDotSize returns the LineDotSize field value if set, zero value otherwise.
func (o *ChartDisplaySettingsLineSettings) GetLineDotSize() int64 {
	if o == nil || IsNil(o.LineDotSize) {
		var ret int64
		return ret
	}
	return *o.LineDotSize
}

// GetLineDotSizeOk returns a tuple with the LineDotSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartDisplaySettingsLineSettings) GetLineDotSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.LineDotSize) {
		return nil, false
	}
	return o.LineDotSize, true
}

// HasLineDotSize returns a boolean if a field has been set.
func (o *ChartDisplaySettingsLineSettings) HasLineDotSize() bool {
	if o != nil && !IsNil(o.LineDotSize) {
		return true
	}

	return false
}

// SetLineDotSize gets a reference to the given int64 and assigns it to the LineDotSize field.
func (o *ChartDisplaySettingsLineSettings) SetLineDotSize(v int64) {
	o.LineDotSize = &v
}

func (o ChartDisplaySettingsLineSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartDisplaySettingsLineSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LineType) {
		toSerialize["lineType"] = o.LineType
	}
	if !IsNil(o.LineColour) {
		toSerialize["lineColour"] = o.LineColour
	}
	if !IsNil(o.LineDotColor) {
		toSerialize["lineDotColor"] = o.LineDotColor
	}
	if !IsNil(o.LineDotSize) {
		toSerialize["lineDotSize"] = o.LineDotSize
	}
	return toSerialize, nil
}

type NullableChartDisplaySettingsLineSettings struct {
	value *ChartDisplaySettingsLineSettings
	isSet bool
}

func (v NullableChartDisplaySettingsLineSettings) Get() *ChartDisplaySettingsLineSettings {
	return v.value
}

func (v *NullableChartDisplaySettingsLineSettings) Set(val *ChartDisplaySettingsLineSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableChartDisplaySettingsLineSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableChartDisplaySettingsLineSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartDisplaySettingsLineSettings(val *ChartDisplaySettingsLineSettings) *NullableChartDisplaySettingsLineSettings {
	return &NullableChartDisplaySettingsLineSettings{value: val, isSet: true}
}

func (v NullableChartDisplaySettingsLineSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartDisplaySettingsLineSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
