/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ValueSettingsMatchingOperatorsInnerRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValueSettingsMatchingOperatorsInnerRange{}

// ValueSettingsMatchingOperatorsInnerRange Range values for comparison when operator is 'range'
type ValueSettingsMatchingOperatorsInnerRange struct {
	// Start value of the range
	From float64 `json:"from"`
	// End value of the range
	To float64 `json:"to"`
}

type _ValueSettingsMatchingOperatorsInnerRange ValueSettingsMatchingOperatorsInnerRange

// NewValueSettingsMatchingOperatorsInnerRange instantiates a new ValueSettingsMatchingOperatorsInnerRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValueSettingsMatchingOperatorsInnerRange(from float64, to float64) *ValueSettingsMatchingOperatorsInnerRange {
	this := ValueSettingsMatchingOperatorsInnerRange{}
	this.From = from
	this.To = to
	return &this
}

// NewValueSettingsMatchingOperatorsInnerRangeWithDefaults instantiates a new ValueSettingsMatchingOperatorsInnerRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValueSettingsMatchingOperatorsInnerRangeWithDefaults() *ValueSettingsMatchingOperatorsInnerRange {
	this := ValueSettingsMatchingOperatorsInnerRange{}
	return &this
}

// GetFrom returns the From field value
func (o *ValueSettingsMatchingOperatorsInnerRange) GetFrom() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *ValueSettingsMatchingOperatorsInnerRange) GetFromOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *ValueSettingsMatchingOperatorsInnerRange) SetFrom(v float64) {
	o.From = v
}

// GetTo returns the To field value
func (o *ValueSettingsMatchingOperatorsInnerRange) GetTo() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *ValueSettingsMatchingOperatorsInnerRange) GetToOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *ValueSettingsMatchingOperatorsInnerRange) SetTo(v float64) {
	o.To = v
}

func (o ValueSettingsMatchingOperatorsInnerRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValueSettingsMatchingOperatorsInnerRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	return toSerialize, nil
}

func (o *ValueSettingsMatchingOperatorsInnerRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValueSettingsMatchingOperatorsInnerRange := _ValueSettingsMatchingOperatorsInnerRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValueSettingsMatchingOperatorsInnerRange)

	if err != nil {
		return err
	}

	*o = ValueSettingsMatchingOperatorsInnerRange(varValueSettingsMatchingOperatorsInnerRange)

	return err
}

type NullableValueSettingsMatchingOperatorsInnerRange struct {
	value *ValueSettingsMatchingOperatorsInnerRange
	isSet bool
}

func (v NullableValueSettingsMatchingOperatorsInnerRange) Get() *ValueSettingsMatchingOperatorsInnerRange {
	return v.value
}

func (v *NullableValueSettingsMatchingOperatorsInnerRange) Set(val *ValueSettingsMatchingOperatorsInnerRange) {
	v.value = val
	v.isSet = true
}

func (v NullableValueSettingsMatchingOperatorsInnerRange) IsSet() bool {
	return v.isSet
}

func (v *NullableValueSettingsMatchingOperatorsInnerRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValueSettingsMatchingOperatorsInnerRange(val *ValueSettingsMatchingOperatorsInnerRange) *NullableValueSettingsMatchingOperatorsInnerRange {
	return &NullableValueSettingsMatchingOperatorsInnerRange{value: val, isSet: true}
}

func (v NullableValueSettingsMatchingOperatorsInnerRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValueSettingsMatchingOperatorsInnerRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
