/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the ChartWidgetDisplaySettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartWidgetDisplaySettings{}

// ChartWidgetDisplaySettings Display settings for chart widget visualization
type ChartWidgetDisplaySettings struct {
	Thresholds *ChartWidgetDisplaySettingsThresholds `json:"thresholds,omitempty"`
}

// NewChartWidgetDisplaySettings instantiates a new ChartWidgetDisplaySettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartWidgetDisplaySettings() *ChartWidgetDisplaySettings {
	this := ChartWidgetDisplaySettings{}
	return &this
}

// NewChartWidgetDisplaySettingsWithDefaults instantiates a new ChartWidgetDisplaySettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartWidgetDisplaySettingsWithDefaults() *ChartWidgetDisplaySettings {
	this := ChartWidgetDisplaySettings{}
	return &this
}

// GetThresholds returns the Thresholds field value if set, zero value otherwise.
func (o *ChartWidgetDisplaySettings) GetThresholds() ChartWidgetDisplaySettingsThresholds {
	if o == nil || IsNil(o.Thresholds) {
		var ret ChartWidgetDisplaySettingsThresholds
		return ret
	}
	return *o.Thresholds
}

// GetThresholdsOk returns a tuple with the Thresholds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidgetDisplaySettings) GetThresholdsOk() (*ChartWidgetDisplaySettingsThresholds, bool) {
	if o == nil || IsNil(o.Thresholds) {
		return nil, false
	}
	return o.Thresholds, true
}

// HasThresholds returns a boolean if a field has been set.
func (o *ChartWidgetDisplaySettings) HasThresholds() bool {
	if o != nil && !IsNil(o.Thresholds) {
		return true
	}

	return false
}

// SetThresholds gets a reference to the given ChartWidgetDisplaySettingsThresholds and assigns it to the Thresholds field.
func (o *ChartWidgetDisplaySettings) SetThresholds(v ChartWidgetDisplaySettingsThresholds) {
	o.Thresholds = &v
}

func (o ChartWidgetDisplaySettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartWidgetDisplaySettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Thresholds) {
		toSerialize["thresholds"] = o.Thresholds
	}
	return toSerialize, nil
}

type NullableChartWidgetDisplaySettings struct {
	value *ChartWidgetDisplaySettings
	isSet bool
}

func (v NullableChartWidgetDisplaySettings) Get() *ChartWidgetDisplaySettings {
	return v.value
}

func (v *NullableChartWidgetDisplaySettings) Set(val *ChartWidgetDisplaySettings) {
	v.value = val
	v.isSet = true
}

func (v NullableChartWidgetDisplaySettings) IsSet() bool {
	return v.isSet
}

func (v *NullableChartWidgetDisplaySettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartWidgetDisplaySettings(val *ChartWidgetDisplaySettings) *NullableChartWidgetDisplaySettings {
	return &NullableChartWidgetDisplaySettings{value: val, isSet: true}
}

func (v NullableChartWidgetDisplaySettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartWidgetDisplaySettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
