/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the ChartWidgetExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartWidgetExpression{}

// ChartWidgetExpression Expression timeseries data to be shown on the chart
type ChartWidgetExpression struct {
	// Array of MetoroQL queries
	MetoroQLQueries []MetoroQLQuery `json:"metoroQLQueries,omitempty"`
}

// NewChartWidgetExpression instantiates a new ChartWidgetExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartWidgetExpression() *ChartWidgetExpression {
	this := ChartWidgetExpression{}
	return &this
}

// NewChartWidgetExpressionWithDefaults instantiates a new ChartWidgetExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartWidgetExpressionWithDefaults() *ChartWidgetExpression {
	this := ChartWidgetExpression{}
	return &this
}

// GetMetoroQLQueries returns the MetoroQLQueries field value if set, zero value otherwise.
func (o *ChartWidgetExpression) GetMetoroQLQueries() []MetoroQLQuery {
	if o == nil || IsNil(o.MetoroQLQueries) {
		var ret []MetoroQLQuery
		return ret
	}
	return o.MetoroQLQueries
}

// GetMetoroQLQueriesOk returns a tuple with the MetoroQLQueries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidgetExpression) GetMetoroQLQueriesOk() ([]MetoroQLQuery, bool) {
	if o == nil || IsNil(o.MetoroQLQueries) {
		return nil, false
	}
	return o.MetoroQLQueries, true
}

// HasMetoroQLQueries returns a boolean if a field has been set.
func (o *ChartWidgetExpression) HasMetoroQLQueries() bool {
	if o != nil && !IsNil(o.MetoroQLQueries) {
		return true
	}

	return false
}

// SetMetoroQLQueries gets a reference to the given []MetoroQLQuery and assigns it to the MetoroQLQueries field.
func (o *ChartWidgetExpression) SetMetoroQLQueries(v []MetoroQLQuery) {
	o.MetoroQLQueries = v
}

func (o ChartWidgetExpression) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartWidgetExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetoroQLQueries) {
		toSerialize["metoroQLQueries"] = o.MetoroQLQueries
	}
	return toSerialize, nil
}

type NullableChartWidgetExpression struct {
	value *ChartWidgetExpression
	isSet bool
}

func (v NullableChartWidgetExpression) Get() *ChartWidgetExpression {
	return v.value
}

func (v *NullableChartWidgetExpression) Set(val *ChartWidgetExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableChartWidgetExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableChartWidgetExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartWidgetExpression(val *ChartWidgetExpression) *NullableChartWidgetExpression {
	return &NullableChartWidgetExpression{value: val, isSet: true}
}

func (v NullableChartWidgetExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartWidgetExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
