/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the TraceWidgetExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TraceWidgetExpression{}

// TraceWidgetExpression Query expression for trace data
type TraceWidgetExpression struct {
	MetoroQLQuery *MetoroQLQuery `json:"metoroQLQuery,omitempty"`
}

// NewTraceWidgetExpression instantiates a new TraceWidgetExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraceWidgetExpression() *TraceWidgetExpression {
	this := TraceWidgetExpression{}
	return &this
}

// NewTraceWidgetExpressionWithDefaults instantiates a new TraceWidgetExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTraceWidgetExpressionWithDefaults() *TraceWidgetExpression {
	this := TraceWidgetExpression{}
	return &this
}

// GetMetoroQLQuery returns the MetoroQLQuery field value if set, zero value otherwise.
func (o *TraceWidgetExpression) GetMetoroQLQuery() MetoroQLQuery {
	if o == nil || IsNil(o.MetoroQLQuery) {
		var ret MetoroQLQuery
		return ret
	}
	return *o.MetoroQLQuery
}

// GetMetoroQLQueryOk returns a tuple with the MetoroQLQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceWidgetExpression) GetMetoroQLQueryOk() (*MetoroQLQuery, bool) {
	if o == nil || IsNil(o.MetoroQLQuery) {
		return nil, false
	}
	return o.MetoroQLQuery, true
}

// HasMetoroQLQuery returns a boolean if a field has been set.
func (o *TraceWidgetExpression) HasMetoroQLQuery() bool {
	if o != nil && !IsNil(o.MetoroQLQuery) {
		return true
	}

	return false
}

// SetMetoroQLQuery gets a reference to the given MetoroQLQuery and assigns it to the MetoroQLQuery field.
func (o *TraceWidgetExpression) SetMetoroQLQuery(v MetoroQLQuery) {
	o.MetoroQLQuery = &v
}

func (o TraceWidgetExpression) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TraceWidgetExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetoroQLQuery) {
		toSerialize["metoroQLQuery"] = o.MetoroQLQuery
	}
	return toSerialize, nil
}

type NullableTraceWidgetExpression struct {
	value *TraceWidgetExpression
	isSet bool
}

func (v NullableTraceWidgetExpression) Get() *TraceWidgetExpression {
	return v.value
}

func (v *NullableTraceWidgetExpression) Set(val *TraceWidgetExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableTraceWidgetExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableTraceWidgetExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraceWidgetExpression(val *TraceWidgetExpression) *NullableTraceWidgetExpression {
	return &NullableTraceWidgetExpression{value: val, isSet: true}
}

func (v NullableTraceWidgetExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraceWidgetExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
