/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the GaugeGlobalSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GaugeGlobalSettings{}

// GaugeGlobalSettings Global display settings for gauge widget
type GaugeGlobalSettings struct {
	// Precision for numeric values
	ValuePrecision *int64 `json:"valuePrecision,omitempty"`
	// Minimum value for gauge
	Min *float64 `json:"min,omitempty"`
	// Maximum value for gauge
	Max *float64 `json:"max,omitempty"`
	// Label for the gauge
	Label *string `json:"label,omitempty"`
	// When true, display raw value instead of percentage
	ShowAbsoluteValue *bool `json:"showAbsoluteValue,omitempty"`
	// Optional unit override for the displayed value
	UnitOverride *string `json:"unitOverride,omitempty"`
}

// NewGaugeGlobalSettings instantiates a new GaugeGlobalSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGaugeGlobalSettings() *GaugeGlobalSettings {
	this := GaugeGlobalSettings{}
	var valuePrecision int64 = 0
	this.ValuePrecision = &valuePrecision
	return &this
}

// NewGaugeGlobalSettingsWithDefaults instantiates a new GaugeGlobalSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGaugeGlobalSettingsWithDefaults() *GaugeGlobalSettings {
	this := GaugeGlobalSettings{}
	var valuePrecision int64 = 0
	this.ValuePrecision = &valuePrecision
	return &this
}

// GetValuePrecision returns the ValuePrecision field value if set, zero value otherwise.
func (o *GaugeGlobalSettings) GetValuePrecision() int64 {
	if o == nil || IsNil(o.ValuePrecision) {
		var ret int64
		return ret
	}
	return *o.ValuePrecision
}

// GetValuePrecisionOk returns a tuple with the ValuePrecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeGlobalSettings) GetValuePrecisionOk() (*int64, bool) {
	if o == nil || IsNil(o.ValuePrecision) {
		return nil, false
	}
	return o.ValuePrecision, true
}

// HasValuePrecision returns a boolean if a field has been set.
func (o *GaugeGlobalSettings) HasValuePrecision() bool {
	if o != nil && !IsNil(o.ValuePrecision) {
		return true
	}

	return false
}

// SetValuePrecision gets a reference to the given int64 and assigns it to the ValuePrecision field.
func (o *GaugeGlobalSettings) SetValuePrecision(v int64) {
	o.ValuePrecision = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *GaugeGlobalSettings) GetMin() float64 {
	if o == nil || IsNil(o.Min) {
		var ret float64
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeGlobalSettings) GetMinOk() (*float64, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *GaugeGlobalSettings) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given float64 and assigns it to the Min field.
func (o *GaugeGlobalSettings) SetMin(v float64) {
	o.Min = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *GaugeGlobalSettings) GetMax() float64 {
	if o == nil || IsNil(o.Max) {
		var ret float64
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeGlobalSettings) GetMaxOk() (*float64, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *GaugeGlobalSettings) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given float64 and assigns it to the Max field.
func (o *GaugeGlobalSettings) SetMax(v float64) {
	o.Max = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *GaugeGlobalSettings) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeGlobalSettings) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *GaugeGlobalSettings) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *GaugeGlobalSettings) SetLabel(v string) {
	o.Label = &v
}

// GetShowAbsoluteValue returns the ShowAbsoluteValue field value if set, zero value otherwise.
func (o *GaugeGlobalSettings) GetShowAbsoluteValue() bool {
	if o == nil || IsNil(o.ShowAbsoluteValue) {
		var ret bool
		return ret
	}
	return *o.ShowAbsoluteValue
}

// GetShowAbsoluteValueOk returns a tuple with the ShowAbsoluteValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeGlobalSettings) GetShowAbsoluteValueOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowAbsoluteValue) {
		return nil, false
	}
	return o.ShowAbsoluteValue, true
}

// HasShowAbsoluteValue returns a boolean if a field has been set.
func (o *GaugeGlobalSettings) HasShowAbsoluteValue() bool {
	if o != nil && !IsNil(o.ShowAbsoluteValue) {
		return true
	}

	return false
}

// SetShowAbsoluteValue gets a reference to the given bool and assigns it to the ShowAbsoluteValue field.
func (o *GaugeGlobalSettings) SetShowAbsoluteValue(v bool) {
	o.ShowAbsoluteValue = &v
}

// GetUnitOverride returns the UnitOverride field value if set, zero value otherwise.
func (o *GaugeGlobalSettings) GetUnitOverride() string {
	if o == nil || IsNil(o.UnitOverride) {
		var ret string
		return ret
	}
	return *o.UnitOverride
}

// GetUnitOverrideOk returns a tuple with the UnitOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeGlobalSettings) GetUnitOverrideOk() (*string, bool) {
	if o == nil || IsNil(o.UnitOverride) {
		return nil, false
	}
	return o.UnitOverride, true
}

// HasUnitOverride returns a boolean if a field has been set.
func (o *GaugeGlobalSettings) HasUnitOverride() bool {
	if o != nil && !IsNil(o.UnitOverride) {
		return true
	}

	return false
}

// SetUnitOverride gets a reference to the given string and assigns it to the UnitOverride field.
func (o *GaugeGlobalSettings) SetUnitOverride(v string) {
	o.UnitOverride = &v
}

func (o GaugeGlobalSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GaugeGlobalSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ValuePrecision) {
		toSerialize["valuePrecision"] = o.ValuePrecision
	}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.ShowAbsoluteValue) {
		toSerialize["showAbsoluteValue"] = o.ShowAbsoluteValue
	}
	if !IsNil(o.UnitOverride) {
		toSerialize["unitOverride"] = o.UnitOverride
	}
	return toSerialize, nil
}

type NullableGaugeGlobalSettings struct {
	value *GaugeGlobalSettings
	isSet bool
}

func (v NullableGaugeGlobalSettings) Get() *GaugeGlobalSettings {
	return v.value
}

func (v *NullableGaugeGlobalSettings) Set(val *GaugeGlobalSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableGaugeGlobalSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableGaugeGlobalSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGaugeGlobalSettings(val *GaugeGlobalSettings) *NullableGaugeGlobalSettings {
	return &NullableGaugeGlobalSettings{value: val, isSet: true}
}

func (v NullableGaugeGlobalSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGaugeGlobalSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
