/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the ValueSettingsColorSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValueSettingsColorSettings{}

// ValueSettingsColorSettings Color settings for matches
type ValueSettingsColorSettings struct {
	// Type of coloring
	Type *string `json:"type,omitempty"`
	// Color value
	Color *string `json:"color,omitempty"`
}

// NewValueSettingsColorSettings instantiates a new ValueSettingsColorSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValueSettingsColorSettings() *ValueSettingsColorSettings {
	this := ValueSettingsColorSettings{}
	return &this
}

// NewValueSettingsColorSettingsWithDefaults instantiates a new ValueSettingsColorSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValueSettingsColorSettingsWithDefaults() *ValueSettingsColorSettings {
	this := ValueSettingsColorSettings{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ValueSettingsColorSettings) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueSettingsColorSettings) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ValueSettingsColorSettings) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ValueSettingsColorSettings) SetType(v string) {
	o.Type = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ValueSettingsColorSettings) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueSettingsColorSettings) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ValueSettingsColorSettings) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ValueSettingsColorSettings) SetColor(v string) {
	o.Color = &v
}

func (o ValueSettingsColorSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValueSettingsColorSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	return toSerialize, nil
}

type NullableValueSettingsColorSettings struct {
	value *ValueSettingsColorSettings
	isSet bool
}

func (v NullableValueSettingsColorSettings) Get() *ValueSettingsColorSettings {
	return v.value
}

func (v *NullableValueSettingsColorSettings) Set(val *ValueSettingsColorSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableValueSettingsColorSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableValueSettingsColorSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValueSettingsColorSettings(val *ValueSettingsColorSettings) *NullableValueSettingsColorSettings {
	return &NullableValueSettingsColorSettings{value: val, isSet: true}
}

func (v NullableValueSettingsColorSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValueSettingsColorSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
