/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the ChartWidgetDisplaySettingsThresholds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartWidgetDisplaySettingsThresholds{}

// ChartWidgetDisplaySettingsThresholds Threshold settings for chart visualization
type ChartWidgetDisplaySettingsThresholds struct {
	// Array of threshold steps
	Steps []ChartWidgetDisplaySettingsThresholdsStepsInner `json:"steps,omitempty"`
}

// NewChartWidgetDisplaySettingsThresholds instantiates a new ChartWidgetDisplaySettingsThresholds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartWidgetDisplaySettingsThresholds() *ChartWidgetDisplaySettingsThresholds {
	this := ChartWidgetDisplaySettingsThresholds{}
	return &this
}

// NewChartWidgetDisplaySettingsThresholdsWithDefaults instantiates a new ChartWidgetDisplaySettingsThresholds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartWidgetDisplaySettingsThresholdsWithDefaults() *ChartWidgetDisplaySettingsThresholds {
	this := ChartWidgetDisplaySettingsThresholds{}
	return &this
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *ChartWidgetDisplaySettingsThresholds) GetSteps() []ChartWidgetDisplaySettingsThresholdsStepsInner {
	if o == nil || IsNil(o.Steps) {
		var ret []ChartWidgetDisplaySettingsThresholdsStepsInner
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidgetDisplaySettingsThresholds) GetStepsOk() ([]ChartWidgetDisplaySettingsThresholdsStepsInner, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *ChartWidgetDisplaySettingsThresholds) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []ChartWidgetDisplaySettingsThresholdsStepsInner and assigns it to the Steps field.
func (o *ChartWidgetDisplaySettingsThresholds) SetSteps(v []ChartWidgetDisplaySettingsThresholdsStepsInner) {
	o.Steps = v
}

func (o ChartWidgetDisplaySettingsThresholds) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartWidgetDisplaySettingsThresholds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	return toSerialize, nil
}

type NullableChartWidgetDisplaySettingsThresholds struct {
	value *ChartWidgetDisplaySettingsThresholds
	isSet bool
}

func (v NullableChartWidgetDisplaySettingsThresholds) Get() *ChartWidgetDisplaySettingsThresholds {
	return v.value
}

func (v *NullableChartWidgetDisplaySettingsThresholds) Set(val *ChartWidgetDisplaySettingsThresholds) {
	v.value = val
	v.isSet = true
}

func (v NullableChartWidgetDisplaySettingsThresholds) IsSet() bool {
	return v.isSet
}

func (v *NullableChartWidgetDisplaySettingsThresholds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartWidgetDisplaySettingsThresholds(val *ChartWidgetDisplaySettingsThresholds) *NullableChartWidgetDisplaySettingsThresholds {
	return &NullableChartWidgetDisplaySettingsThresholds{value: val, isSet: true}
}

func (v NullableChartWidgetDisplaySettingsThresholds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartWidgetDisplaySettingsThresholds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
