/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PositionAbsolute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PositionAbsolute{}

// PositionAbsolute Absolute positioning coordinates. Each dashboard and a GroupWidget consists of 12 columns and 12 rows.
type PositionAbsolute struct {
	// X coordinate (0-12)
	X int32 `json:"x"`
	// Y coordinate (0-12)
	Y int32 `json:"y"`
	// Width (0-12)
	W int32 `json:"w"`
	// Height (0-12)
	H int32 `json:"h"`
}

type _PositionAbsolute PositionAbsolute

// NewPositionAbsolute instantiates a new PositionAbsolute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPositionAbsolute(x int32, y int32, w int32, h int32) *PositionAbsolute {
	this := PositionAbsolute{}
	this.X = x
	this.Y = y
	this.W = w
	this.H = h
	return &this
}

// NewPositionAbsoluteWithDefaults instantiates a new PositionAbsolute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPositionAbsoluteWithDefaults() *PositionAbsolute {
	this := PositionAbsolute{}
	return &this
}

// GetX returns the X field value
func (o *PositionAbsolute) GetX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *PositionAbsolute) GetXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *PositionAbsolute) SetX(v int32) {
	o.X = v
}

// GetY returns the Y field value
func (o *PositionAbsolute) GetY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *PositionAbsolute) GetYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *PositionAbsolute) SetY(v int32) {
	o.Y = v
}

// GetW returns the W field value
func (o *PositionAbsolute) GetW() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.W
}

// GetWOk returns a tuple with the W field value
// and a boolean to check if the value has been set.
func (o *PositionAbsolute) GetWOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.W, true
}

// SetW sets field value
func (o *PositionAbsolute) SetW(v int32) {
	o.W = v
}

// GetH returns the H field value
func (o *PositionAbsolute) GetH() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.H
}

// GetHOk returns a tuple with the H field value
// and a boolean to check if the value has been set.
func (o *PositionAbsolute) GetHOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.H, true
}

// SetH sets field value
func (o *PositionAbsolute) SetH(v int32) {
	o.H = v
}

func (o PositionAbsolute) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PositionAbsolute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	toSerialize["w"] = o.W
	toSerialize["h"] = o.H
	return toSerialize, nil
}

func (o *PositionAbsolute) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x",
		"y",
		"w",
		"h",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPositionAbsolute := _PositionAbsolute{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPositionAbsolute)

	if err != nil {
		return err
	}

	*o = PositionAbsolute(varPositionAbsolute)

	return err
}

type NullablePositionAbsolute struct {
	value *PositionAbsolute
	isSet bool
}

func (v NullablePositionAbsolute) Get() *PositionAbsolute {
	return v.value
}

func (v *NullablePositionAbsolute) Set(val *PositionAbsolute) {
	v.value = val
	v.isSet = true
}

func (v NullablePositionAbsolute) IsSet() bool {
	return v.isSet
}

func (v *NullablePositionAbsolute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePositionAbsolute(val *PositionAbsolute) *NullablePositionAbsolute {
	return &NullablePositionAbsolute{value: val, isSet: true}
}

func (v NullablePositionAbsolute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePositionAbsolute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
