/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ColumnVisualSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ColumnVisualSetting{}

// ColumnVisualSetting Visual settings for a column
type ColumnVisualSetting struct {
	// Column identifier
	Column string `json:"column"`
	// Display title for column
	Title *string `json:"title,omitempty"`
	// Whether column is hidden by default
	HiddenByDefault *bool `json:"hiddenByDefault,omitempty"`
	// Regex pattern for extracting values
	RegexExtractor *string `json:"regexExtractor,omitempty"`
}

type _ColumnVisualSetting ColumnVisualSetting

// NewColumnVisualSetting instantiates a new ColumnVisualSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewColumnVisualSetting(column string) *ColumnVisualSetting {
	this := ColumnVisualSetting{}
	this.Column = column
	return &this
}

// NewColumnVisualSettingWithDefaults instantiates a new ColumnVisualSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewColumnVisualSettingWithDefaults() *ColumnVisualSetting {
	this := ColumnVisualSetting{}
	return &this
}

// GetColumn returns the Column field value
func (o *ColumnVisualSetting) GetColumn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Column
}

// GetColumnOk returns a tuple with the Column field value
// and a boolean to check if the value has been set.
func (o *ColumnVisualSetting) GetColumnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Column, true
}

// SetColumn sets field value
func (o *ColumnVisualSetting) SetColumn(v string) {
	o.Column = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ColumnVisualSetting) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnVisualSetting) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ColumnVisualSetting) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ColumnVisualSetting) SetTitle(v string) {
	o.Title = &v
}

// GetHiddenByDefault returns the HiddenByDefault field value if set, zero value otherwise.
func (o *ColumnVisualSetting) GetHiddenByDefault() bool {
	if o == nil || IsNil(o.HiddenByDefault) {
		var ret bool
		return ret
	}
	return *o.HiddenByDefault
}

// GetHiddenByDefaultOk returns a tuple with the HiddenByDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnVisualSetting) GetHiddenByDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.HiddenByDefault) {
		return nil, false
	}
	return o.HiddenByDefault, true
}

// HasHiddenByDefault returns a boolean if a field has been set.
func (o *ColumnVisualSetting) HasHiddenByDefault() bool {
	if o != nil && !IsNil(o.HiddenByDefault) {
		return true
	}

	return false
}

// SetHiddenByDefault gets a reference to the given bool and assigns it to the HiddenByDefault field.
func (o *ColumnVisualSetting) SetHiddenByDefault(v bool) {
	o.HiddenByDefault = &v
}

// GetRegexExtractor returns the RegexExtractor field value if set, zero value otherwise.
func (o *ColumnVisualSetting) GetRegexExtractor() string {
	if o == nil || IsNil(o.RegexExtractor) {
		var ret string
		return ret
	}
	return *o.RegexExtractor
}

// GetRegexExtractorOk returns a tuple with the RegexExtractor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnVisualSetting) GetRegexExtractorOk() (*string, bool) {
	if o == nil || IsNil(o.RegexExtractor) {
		return nil, false
	}
	return o.RegexExtractor, true
}

// HasRegexExtractor returns a boolean if a field has been set.
func (o *ColumnVisualSetting) HasRegexExtractor() bool {
	if o != nil && !IsNil(o.RegexExtractor) {
		return true
	}

	return false
}

// SetRegexExtractor gets a reference to the given string and assigns it to the RegexExtractor field.
func (o *ColumnVisualSetting) SetRegexExtractor(v string) {
	o.RegexExtractor = &v
}

func (o ColumnVisualSetting) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ColumnVisualSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["column"] = o.Column
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.HiddenByDefault) {
		toSerialize["hiddenByDefault"] = o.HiddenByDefault
	}
	if !IsNil(o.RegexExtractor) {
		toSerialize["regexExtractor"] = o.RegexExtractor
	}
	return toSerialize, nil
}

func (o *ColumnVisualSetting) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"column",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varColumnVisualSetting := _ColumnVisualSetting{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varColumnVisualSetting)

	if err != nil {
		return err
	}

	*o = ColumnVisualSetting(varColumnVisualSetting)

	return err
}

type NullableColumnVisualSetting struct {
	value *ColumnVisualSetting
	isSet bool
}

func (v NullableColumnVisualSetting) Get() *ColumnVisualSetting {
	return v.value
}

func (v *NullableColumnVisualSetting) Set(val *ColumnVisualSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableColumnVisualSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableColumnVisualSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColumnVisualSetting(val *ColumnVisualSetting) *NullableColumnVisualSetting {
	return &NullableColumnVisualSetting{value: val, isSet: true}
}

func (v NullableColumnVisualSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColumnVisualSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
