/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the VariableSelector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariableSelector{}

// VariableSelector struct for VariableSelector
type VariableSelector struct {
	Dynamic *DynamicVariableSelectorSettings `json:"dynamic,omitempty"`
}

// NewVariableSelector instantiates a new VariableSelector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariableSelector() *VariableSelector {
	this := VariableSelector{}
	return &this
}

// NewVariableSelectorWithDefaults instantiates a new VariableSelector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableSelectorWithDefaults() *VariableSelector {
	this := VariableSelector{}
	return &this
}

// GetDynamic returns the Dynamic field value if set, zero value otherwise.
func (o *VariableSelector) GetDynamic() DynamicVariableSelectorSettings {
	if o == nil || IsNil(o.Dynamic) {
		var ret DynamicVariableSelectorSettings
		return ret
	}
	return *o.Dynamic
}

// GetDynamicOk returns a tuple with the Dynamic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariableSelector) GetDynamicOk() (*DynamicVariableSelectorSettings, bool) {
	if o == nil || IsNil(o.Dynamic) {
		return nil, false
	}
	return o.Dynamic, true
}

// HasDynamic returns a boolean if a field has been set.
func (o *VariableSelector) HasDynamic() bool {
	if o != nil && !IsNil(o.Dynamic) {
		return true
	}

	return false
}

// SetDynamic gets a reference to the given DynamicVariableSelectorSettings and assigns it to the Dynamic field.
func (o *VariableSelector) SetDynamic(v DynamicVariableSelectorSettings) {
	o.Dynamic = &v
}

func (o VariableSelector) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariableSelector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dynamic) {
		toSerialize["dynamic"] = o.Dynamic
	}
	return toSerialize, nil
}

type NullableVariableSelector struct {
	value *VariableSelector
	isSet bool
}

func (v NullableVariableSelector) Get() *VariableSelector {
	return v.value
}

func (v *NullableVariableSelector) Set(val *VariableSelector) {
	v.value = val
	v.isSet = true
}

func (v NullableVariableSelector) IsSet() bool {
	return v.isSet
}

func (v *NullableVariableSelector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariableSelector(val *VariableSelector) *NullableVariableSelector {
	return &NullableVariableSelector{value: val, isSet: true}
}

func (v NullableVariableSelector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariableSelector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
