/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the ValueSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValueSettings{}

// ValueSettings Settings for conditional value formatting
type ValueSettings struct {
	// Operators for matching conditions
	MatchingOperators []ValueSettingsMatchingOperatorsInner `json:"matchingOperators,omitempty"`
	ColorSettings     *ValueSettingsColorSettings           `json:"colorSettings,omitempty"`
	// Format string for value display
	FormatSpecifier *string `json:"formatSpecifier,omitempty"`
}

// NewValueSettings instantiates a new ValueSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValueSettings() *ValueSettings {
	this := ValueSettings{}
	return &this
}

// NewValueSettingsWithDefaults instantiates a new ValueSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValueSettingsWithDefaults() *ValueSettings {
	this := ValueSettings{}
	return &this
}

// GetMatchingOperators returns the MatchingOperators field value if set, zero value otherwise.
func (o *ValueSettings) GetMatchingOperators() []ValueSettingsMatchingOperatorsInner {
	if o == nil || IsNil(o.MatchingOperators) {
		var ret []ValueSettingsMatchingOperatorsInner
		return ret
	}
	return o.MatchingOperators
}

// GetMatchingOperatorsOk returns a tuple with the MatchingOperators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueSettings) GetMatchingOperatorsOk() ([]ValueSettingsMatchingOperatorsInner, bool) {
	if o == nil || IsNil(o.MatchingOperators) {
		return nil, false
	}
	return o.MatchingOperators, true
}

// HasMatchingOperators returns a boolean if a field has been set.
func (o *ValueSettings) HasMatchingOperators() bool {
	if o != nil && !IsNil(o.MatchingOperators) {
		return true
	}

	return false
}

// SetMatchingOperators gets a reference to the given []ValueSettingsMatchingOperatorsInner and assigns it to the MatchingOperators field.
func (o *ValueSettings) SetMatchingOperators(v []ValueSettingsMatchingOperatorsInner) {
	o.MatchingOperators = v
}

// GetColorSettings returns the ColorSettings field value if set, zero value otherwise.
func (o *ValueSettings) GetColorSettings() ValueSettingsColorSettings {
	if o == nil || IsNil(o.ColorSettings) {
		var ret ValueSettingsColorSettings
		return ret
	}
	return *o.ColorSettings
}

// GetColorSettingsOk returns a tuple with the ColorSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueSettings) GetColorSettingsOk() (*ValueSettingsColorSettings, bool) {
	if o == nil || IsNil(o.ColorSettings) {
		return nil, false
	}
	return o.ColorSettings, true
}

// HasColorSettings returns a boolean if a field has been set.
func (o *ValueSettings) HasColorSettings() bool {
	if o != nil && !IsNil(o.ColorSettings) {
		return true
	}

	return false
}

// SetColorSettings gets a reference to the given ValueSettingsColorSettings and assigns it to the ColorSettings field.
func (o *ValueSettings) SetColorSettings(v ValueSettingsColorSettings) {
	o.ColorSettings = &v
}

// GetFormatSpecifier returns the FormatSpecifier field value if set, zero value otherwise.
func (o *ValueSettings) GetFormatSpecifier() string {
	if o == nil || IsNil(o.FormatSpecifier) {
		var ret string
		return ret
	}
	return *o.FormatSpecifier
}

// GetFormatSpecifierOk returns a tuple with the FormatSpecifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueSettings) GetFormatSpecifierOk() (*string, bool) {
	if o == nil || IsNil(o.FormatSpecifier) {
		return nil, false
	}
	return o.FormatSpecifier, true
}

// HasFormatSpecifier returns a boolean if a field has been set.
func (o *ValueSettings) HasFormatSpecifier() bool {
	if o != nil && !IsNil(o.FormatSpecifier) {
		return true
	}

	return false
}

// SetFormatSpecifier gets a reference to the given string and assigns it to the FormatSpecifier field.
func (o *ValueSettings) SetFormatSpecifier(v string) {
	o.FormatSpecifier = &v
}

func (o ValueSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValueSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MatchingOperators) {
		toSerialize["matchingOperators"] = o.MatchingOperators
	}
	if !IsNil(o.ColorSettings) {
		toSerialize["colorSettings"] = o.ColorSettings
	}
	if !IsNil(o.FormatSpecifier) {
		toSerialize["formatSpecifier"] = o.FormatSpecifier
	}
	return toSerialize, nil
}

type NullableValueSettings struct {
	value *ValueSettings
	isSet bool
}

func (v NullableValueSettings) Get() *ValueSettings {
	return v.value
}

func (v *NullableValueSettings) Set(val *ValueSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableValueSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableValueSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValueSettings(val *ValueSettings) *NullableValueSettings {
	return &NullableValueSettings{value: val, isSet: true}
}

func (v NullableValueSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValueSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
