/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DashboardMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardMetadata{}

// DashboardMetadata Metadata for dashboard
type DashboardMetadata struct {
	// Dashboard title
	Title *string `json:"title,omitempty"`
	// Unique identifier for the dashboard
	Id string `json:"id"`
	// Path to the folder where the dashboard is stored. Must start with `/dashboards/`. Must end with `/`. The generated filesystem path will be `{folderPath}{id}`.
	FolderPath *string `json:"folderPath,omitempty" validate:"regexp=dashboards/.*"`
}

type _DashboardMetadata DashboardMetadata

// NewDashboardMetadata instantiates a new DashboardMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardMetadata(id string) *DashboardMetadata {
	this := DashboardMetadata{}
	this.Id = id
	var folderPath string = "/dashboards/default/"
	this.FolderPath = &folderPath
	return &this
}

// NewDashboardMetadataWithDefaults instantiates a new DashboardMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardMetadataWithDefaults() *DashboardMetadata {
	this := DashboardMetadata{}
	var folderPath string = "/dashboards/default/"
	this.FolderPath = &folderPath
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *DashboardMetadata) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardMetadata) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *DashboardMetadata) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *DashboardMetadata) SetTitle(v string) {
	o.Title = &v
}

// GetId returns the Id field value
func (o *DashboardMetadata) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DashboardMetadata) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DashboardMetadata) SetId(v string) {
	o.Id = v
}

// GetFolderPath returns the FolderPath field value if set, zero value otherwise.
func (o *DashboardMetadata) GetFolderPath() string {
	if o == nil || IsNil(o.FolderPath) {
		var ret string
		return ret
	}
	return *o.FolderPath
}

// GetFolderPathOk returns a tuple with the FolderPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardMetadata) GetFolderPathOk() (*string, bool) {
	if o == nil || IsNil(o.FolderPath) {
		return nil, false
	}
	return o.FolderPath, true
}

// HasFolderPath returns a boolean if a field has been set.
func (o *DashboardMetadata) HasFolderPath() bool {
	if o != nil && !IsNil(o.FolderPath) {
		return true
	}

	return false
}

// SetFolderPath gets a reference to the given string and assigns it to the FolderPath field.
func (o *DashboardMetadata) SetFolderPath(v string) {
	o.FolderPath = &v
}

func (o DashboardMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.FolderPath) {
		toSerialize["folderPath"] = o.FolderPath
	}
	return toSerialize, nil
}

func (o *DashboardMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDashboardMetadata := _DashboardMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDashboardMetadata)

	if err != nil {
		return err
	}

	*o = DashboardMetadata(varDashboardMetadata)

	return err
}

type NullableDashboardMetadata struct {
	value *DashboardMetadata
	isSet bool
}

func (v NullableDashboardMetadata) Get() *DashboardMetadata {
	return v.value
}

func (v *NullableDashboardMetadata) Set(val *DashboardMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardMetadata(val *DashboardMetadata) *NullableDashboardMetadata {
	return &NullableDashboardMetadata{value: val, isSet: true}
}

func (v NullableDashboardMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
