/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ValueSettingsMatchingOperatorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValueSettingsMatchingOperatorsInner{}

// ValueSettingsMatchingOperatorsInner struct for ValueSettingsMatchingOperatorsInner
type ValueSettingsMatchingOperatorsInner struct {
	// Comparison operator
	Operator string `json:"operator"`
	// Threshold value for comparison (used with operators other than 'range')
	Threshold *float64                                  `json:"threshold,omitempty"`
	Range     *ValueSettingsMatchingOperatorsInnerRange `json:"range,omitempty"`
}

type _ValueSettingsMatchingOperatorsInner ValueSettingsMatchingOperatorsInner

// NewValueSettingsMatchingOperatorsInner instantiates a new ValueSettingsMatchingOperatorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValueSettingsMatchingOperatorsInner(operator string) *ValueSettingsMatchingOperatorsInner {
	this := ValueSettingsMatchingOperatorsInner{}
	this.Operator = operator
	return &this
}

// NewValueSettingsMatchingOperatorsInnerWithDefaults instantiates a new ValueSettingsMatchingOperatorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValueSettingsMatchingOperatorsInnerWithDefaults() *ValueSettingsMatchingOperatorsInner {
	this := ValueSettingsMatchingOperatorsInner{}
	return &this
}

// GetOperator returns the Operator field value
func (o *ValueSettingsMatchingOperatorsInner) GetOperator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *ValueSettingsMatchingOperatorsInner) GetOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *ValueSettingsMatchingOperatorsInner) SetOperator(v string) {
	o.Operator = v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *ValueSettingsMatchingOperatorsInner) GetThreshold() float64 {
	if o == nil || IsNil(o.Threshold) {
		var ret float64
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueSettingsMatchingOperatorsInner) GetThresholdOk() (*float64, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *ValueSettingsMatchingOperatorsInner) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given float64 and assigns it to the Threshold field.
func (o *ValueSettingsMatchingOperatorsInner) SetThreshold(v float64) {
	o.Threshold = &v
}

// GetRange returns the Range field value if set, zero value otherwise.
func (o *ValueSettingsMatchingOperatorsInner) GetRange() ValueSettingsMatchingOperatorsInnerRange {
	if o == nil || IsNil(o.Range) {
		var ret ValueSettingsMatchingOperatorsInnerRange
		return ret
	}
	return *o.Range
}

// GetRangeOk returns a tuple with the Range field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueSettingsMatchingOperatorsInner) GetRangeOk() (*ValueSettingsMatchingOperatorsInnerRange, bool) {
	if o == nil || IsNil(o.Range) {
		return nil, false
	}
	return o.Range, true
}

// HasRange returns a boolean if a field has been set.
func (o *ValueSettingsMatchingOperatorsInner) HasRange() bool {
	if o != nil && !IsNil(o.Range) {
		return true
	}

	return false
}

// SetRange gets a reference to the given ValueSettingsMatchingOperatorsInnerRange and assigns it to the Range field.
func (o *ValueSettingsMatchingOperatorsInner) SetRange(v ValueSettingsMatchingOperatorsInnerRange) {
	o.Range = &v
}

func (o ValueSettingsMatchingOperatorsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValueSettingsMatchingOperatorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operator"] = o.Operator
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.Range) {
		toSerialize["range"] = o.Range
	}
	return toSerialize, nil
}

func (o *ValueSettingsMatchingOperatorsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValueSettingsMatchingOperatorsInner := _ValueSettingsMatchingOperatorsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValueSettingsMatchingOperatorsInner)

	if err != nil {
		return err
	}

	*o = ValueSettingsMatchingOperatorsInner(varValueSettingsMatchingOperatorsInner)

	return err
}

type NullableValueSettingsMatchingOperatorsInner struct {
	value *ValueSettingsMatchingOperatorsInner
	isSet bool
}

func (v NullableValueSettingsMatchingOperatorsInner) Get() *ValueSettingsMatchingOperatorsInner {
	return v.value
}

func (v *NullableValueSettingsMatchingOperatorsInner) Set(val *ValueSettingsMatchingOperatorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableValueSettingsMatchingOperatorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableValueSettingsMatchingOperatorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValueSettingsMatchingOperatorsInner(val *ValueSettingsMatchingOperatorsInner) *NullableValueSettingsMatchingOperatorsInner {
	return &NullableValueSettingsMatchingOperatorsInner{value: val, isSet: true}
}

func (v NullableValueSettingsMatchingOperatorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValueSettingsMatchingOperatorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
