/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the GroupWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupWidget{}

// GroupWidget Widget for grouping other widgets
type GroupWidget struct {
	// Group title
	Title *string `json:"title,omitempty"`
	// Array of widgets in the group
	Widgets []Widget `json:"widgets,omitempty"`
	// Variables available in this group
	Variables []Variable `json:"variables,omitempty"`
}

// NewGroupWidget instantiates a new GroupWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupWidget() *GroupWidget {
	this := GroupWidget{}
	return &this
}

// NewGroupWidgetWithDefaults instantiates a new GroupWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupWidgetWithDefaults() *GroupWidget {
	this := GroupWidget{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GroupWidget) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupWidget) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GroupWidget) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GroupWidget) SetTitle(v string) {
	o.Title = &v
}

// GetWidgets returns the Widgets field value if set, zero value otherwise.
func (o *GroupWidget) GetWidgets() []Widget {
	if o == nil || IsNil(o.Widgets) {
		var ret []Widget
		return ret
	}
	return o.Widgets
}

// GetWidgetsOk returns a tuple with the Widgets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupWidget) GetWidgetsOk() ([]Widget, bool) {
	if o == nil || IsNil(o.Widgets) {
		return nil, false
	}
	return o.Widgets, true
}

// HasWidgets returns a boolean if a field has been set.
func (o *GroupWidget) HasWidgets() bool {
	if o != nil && !IsNil(o.Widgets) {
		return true
	}

	return false
}

// SetWidgets gets a reference to the given []Widget and assigns it to the Widgets field.
func (o *GroupWidget) SetWidgets(v []Widget) {
	o.Widgets = v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *GroupWidget) GetVariables() []Variable {
	if o == nil || IsNil(o.Variables) {
		var ret []Variable
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupWidget) GetVariablesOk() ([]Variable, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *GroupWidget) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []Variable and assigns it to the Variables field.
func (o *GroupWidget) SetVariables(v []Variable) {
	o.Variables = v
}

func (o GroupWidget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Widgets) {
		toSerialize["widgets"] = o.Widgets
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

type NullableGroupWidget struct {
	value *GroupWidget
	isSet bool
}

func (v NullableGroupWidget) Get() *GroupWidget {
	return v.value
}

func (v *NullableGroupWidget) Set(val *GroupWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupWidget(val *GroupWidget) *NullableGroupWidget {
	return &NullableGroupWidget{value: val, isSet: true}
}

func (v NullableGroupWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
