/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the LogWidgetExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogWidgetExpression{}

// LogWidgetExpression Query expression for log data
type LogWidgetExpression struct {
	MetoroQLQuery *MetoroQLQuery `json:"metoroQLQuery,omitempty"`
}

// NewLogWidgetExpression instantiates a new LogWidgetExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogWidgetExpression() *LogWidgetExpression {
	this := LogWidgetExpression{}
	return &this
}

// NewLogWidgetExpressionWithDefaults instantiates a new LogWidgetExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogWidgetExpressionWithDefaults() *LogWidgetExpression {
	this := LogWidgetExpression{}
	return &this
}

// GetMetoroQLQuery returns the MetoroQLQuery field value if set, zero value otherwise.
func (o *LogWidgetExpression) GetMetoroQLQuery() MetoroQLQuery {
	if o == nil || IsNil(o.MetoroQLQuery) {
		var ret MetoroQLQuery
		return ret
	}
	return *o.MetoroQLQuery
}

// GetMetoroQLQueryOk returns a tuple with the MetoroQLQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogWidgetExpression) GetMetoroQLQueryOk() (*MetoroQLQuery, bool) {
	if o == nil || IsNil(o.MetoroQLQuery) {
		return nil, false
	}
	return o.MetoroQLQuery, true
}

// HasMetoroQLQuery returns a boolean if a field has been set.
func (o *LogWidgetExpression) HasMetoroQLQuery() bool {
	if o != nil && !IsNil(o.MetoroQLQuery) {
		return true
	}

	return false
}

// SetMetoroQLQuery gets a reference to the given MetoroQLQuery and assigns it to the MetoroQLQuery field.
func (o *LogWidgetExpression) SetMetoroQLQuery(v MetoroQLQuery) {
	o.MetoroQLQuery = &v
}

func (o LogWidgetExpression) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogWidgetExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetoroQLQuery) {
		toSerialize["metoroQLQuery"] = o.MetoroQLQuery
	}
	return toSerialize, nil
}

type NullableLogWidgetExpression struct {
	value *LogWidgetExpression
	isSet bool
}

func (v NullableLogWidgetExpression) Get() *LogWidgetExpression {
	return v.value
}

func (v *NullableLogWidgetExpression) Set(val *LogWidgetExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableLogWidgetExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableLogWidgetExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogWidgetExpression(val *LogWidgetExpression) *NullableLogWidgetExpression {
	return &NullableLogWidgetExpression{value: val, isSet: true}
}

func (v NullableLogWidgetExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogWidgetExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
