/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the ChartDisplaySettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartDisplaySettings{}

// ChartDisplaySettings Display settings for chart visualization
type ChartDisplaySettings struct {
	// Label for the metric on the legend
	Label        *string                           `json:"label,omitempty"`
	LineSettings *ChartDisplaySettingsLineSettings `json:"lineSettings,omitempty"`
	// if specified, this unit will be used instead of the backend-provided unit
	UnitOverride *string `json:"unitOverride,omitempty"`
}

// NewChartDisplaySettings instantiates a new ChartDisplaySettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartDisplaySettings() *ChartDisplaySettings {
	this := ChartDisplaySettings{}
	return &this
}

// NewChartDisplaySettingsWithDefaults instantiates a new ChartDisplaySettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartDisplaySettingsWithDefaults() *ChartDisplaySettings {
	this := ChartDisplaySettings{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ChartDisplaySettings) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartDisplaySettings) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ChartDisplaySettings) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *ChartDisplaySettings) SetLabel(v string) {
	o.Label = &v
}

// GetLineSettings returns the LineSettings field value if set, zero value otherwise.
func (o *ChartDisplaySettings) GetLineSettings() ChartDisplaySettingsLineSettings {
	if o == nil || IsNil(o.LineSettings) {
		var ret ChartDisplaySettingsLineSettings
		return ret
	}
	return *o.LineSettings
}

// GetLineSettingsOk returns a tuple with the LineSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartDisplaySettings) GetLineSettingsOk() (*ChartDisplaySettingsLineSettings, bool) {
	if o == nil || IsNil(o.LineSettings) {
		return nil, false
	}
	return o.LineSettings, true
}

// HasLineSettings returns a boolean if a field has been set.
func (o *ChartDisplaySettings) HasLineSettings() bool {
	if o != nil && !IsNil(o.LineSettings) {
		return true
	}

	return false
}

// SetLineSettings gets a reference to the given ChartDisplaySettingsLineSettings and assigns it to the LineSettings field.
func (o *ChartDisplaySettings) SetLineSettings(v ChartDisplaySettingsLineSettings) {
	o.LineSettings = &v
}

// GetUnitOverride returns the UnitOverride field value if set, zero value otherwise.
func (o *ChartDisplaySettings) GetUnitOverride() string {
	if o == nil || IsNil(o.UnitOverride) {
		var ret string
		return ret
	}
	return *o.UnitOverride
}

// GetUnitOverrideOk returns a tuple with the UnitOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartDisplaySettings) GetUnitOverrideOk() (*string, bool) {
	if o == nil || IsNil(o.UnitOverride) {
		return nil, false
	}
	return o.UnitOverride, true
}

// HasUnitOverride returns a boolean if a field has been set.
func (o *ChartDisplaySettings) HasUnitOverride() bool {
	if o != nil && !IsNil(o.UnitOverride) {
		return true
	}

	return false
}

// SetUnitOverride gets a reference to the given string and assigns it to the UnitOverride field.
func (o *ChartDisplaySettings) SetUnitOverride(v string) {
	o.UnitOverride = &v
}

func (o ChartDisplaySettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartDisplaySettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.LineSettings) {
		toSerialize["lineSettings"] = o.LineSettings
	}
	if !IsNil(o.UnitOverride) {
		toSerialize["unitOverride"] = o.UnitOverride
	}
	return toSerialize, nil
}

type NullableChartDisplaySettings struct {
	value *ChartDisplaySettings
	isSet bool
}

func (v NullableChartDisplaySettings) Get() *ChartDisplaySettings {
	return v.value
}

func (v *NullableChartDisplaySettings) Set(val *ChartDisplaySettings) {
	v.value = val
	v.isSet = true
}

func (v NullableChartDisplaySettings) IsSet() bool {
	return v.isSet
}

func (v *NullableChartDisplaySettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartDisplaySettings(val *ChartDisplaySettings) *NullableChartDisplaySettings {
	return &NullableChartDisplaySettings{value: val, isSet: true}
}

func (v NullableChartDisplaySettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartDisplaySettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
