/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the StatWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatWidget{}

// StatWidget Widget for displaying statistics
type StatWidget struct {
	// Stat title
	Title           *string               `json:"title,omitempty"`
	Expression      *StatWidgetExpression `json:"expression,omitempty"`
	DisplaySettings *StatDisplaySettings  `json:"displaySettings,omitempty"`
}

// NewStatWidget instantiates a new StatWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatWidget() *StatWidget {
	this := StatWidget{}
	return &this
}

// NewStatWidgetWithDefaults instantiates a new StatWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatWidgetWithDefaults() *StatWidget {
	this := StatWidget{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *StatWidget) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatWidget) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *StatWidget) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *StatWidget) SetTitle(v string) {
	o.Title = &v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *StatWidget) GetExpression() StatWidgetExpression {
	if o == nil || IsNil(o.Expression) {
		var ret StatWidgetExpression
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatWidget) GetExpressionOk() (*StatWidgetExpression, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *StatWidget) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given StatWidgetExpression and assigns it to the Expression field.
func (o *StatWidget) SetExpression(v StatWidgetExpression) {
	o.Expression = &v
}

// GetDisplaySettings returns the DisplaySettings field value if set, zero value otherwise.
func (o *StatWidget) GetDisplaySettings() StatDisplaySettings {
	if o == nil || IsNil(o.DisplaySettings) {
		var ret StatDisplaySettings
		return ret
	}
	return *o.DisplaySettings
}

// GetDisplaySettingsOk returns a tuple with the DisplaySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatWidget) GetDisplaySettingsOk() (*StatDisplaySettings, bool) {
	if o == nil || IsNil(o.DisplaySettings) {
		return nil, false
	}
	return o.DisplaySettings, true
}

// HasDisplaySettings returns a boolean if a field has been set.
func (o *StatWidget) HasDisplaySettings() bool {
	if o != nil && !IsNil(o.DisplaySettings) {
		return true
	}

	return false
}

// SetDisplaySettings gets a reference to the given StatDisplaySettings and assigns it to the DisplaySettings field.
func (o *StatWidget) SetDisplaySettings(v StatDisplaySettings) {
	o.DisplaySettings = &v
}

func (o StatWidget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.DisplaySettings) {
		toSerialize["displaySettings"] = o.DisplaySettings
	}
	return toSerialize, nil
}

type NullableStatWidget struct {
	value *StatWidget
	isSet bool
}

func (v NullableStatWidget) Get() *StatWidget {
	return v.value
}

func (v *NullableStatWidget) Set(val *StatWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableStatWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableStatWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatWidget(val *StatWidget) *NullableStatWidget {
	return &NullableStatWidget{value: val, isSet: true}
}

func (v NullableStatWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
