/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DynamicVariableSelectorSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DynamicVariableSelectorSettings{}

// DynamicVariableSelectorSettings Settings for dynamic variable value selection
type DynamicVariableSelectorSettings struct {
	// Array of MetoroQL query strings (should have exactly 1 element)
	SelectorQueries []string `json:"selectorQueries"`
	// Key of the attribute to use for value selection
	AttributeKey string `json:"attributeKey"`
}

type _DynamicVariableSelectorSettings DynamicVariableSelectorSettings

// NewDynamicVariableSelectorSettings instantiates a new DynamicVariableSelectorSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDynamicVariableSelectorSettings(selectorQueries []string, attributeKey string) *DynamicVariableSelectorSettings {
	this := DynamicVariableSelectorSettings{}
	this.SelectorQueries = selectorQueries
	this.AttributeKey = attributeKey
	return &this
}

// NewDynamicVariableSelectorSettingsWithDefaults instantiates a new DynamicVariableSelectorSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDynamicVariableSelectorSettingsWithDefaults() *DynamicVariableSelectorSettings {
	this := DynamicVariableSelectorSettings{}
	return &this
}

// GetSelectorQueries returns the SelectorQueries field value
func (o *DynamicVariableSelectorSettings) GetSelectorQueries() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SelectorQueries
}

// GetSelectorQueriesOk returns a tuple with the SelectorQueries field value
// and a boolean to check if the value has been set.
func (o *DynamicVariableSelectorSettings) GetSelectorQueriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelectorQueries, true
}

// SetSelectorQueries sets field value
func (o *DynamicVariableSelectorSettings) SetSelectorQueries(v []string) {
	o.SelectorQueries = v
}

// GetAttributeKey returns the AttributeKey field value
func (o *DynamicVariableSelectorSettings) GetAttributeKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeKey
}

// GetAttributeKeyOk returns a tuple with the AttributeKey field value
// and a boolean to check if the value has been set.
func (o *DynamicVariableSelectorSettings) GetAttributeKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeKey, true
}

// SetAttributeKey sets field value
func (o *DynamicVariableSelectorSettings) SetAttributeKey(v string) {
	o.AttributeKey = v
}

func (o DynamicVariableSelectorSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DynamicVariableSelectorSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["selectorQueries"] = o.SelectorQueries
	toSerialize["attributeKey"] = o.AttributeKey
	return toSerialize, nil
}

func (o *DynamicVariableSelectorSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selectorQueries",
		"attributeKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDynamicVariableSelectorSettings := _DynamicVariableSelectorSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDynamicVariableSelectorSettings)

	if err != nil {
		return err
	}

	*o = DynamicVariableSelectorSettings(varDynamicVariableSelectorSettings)

	return err
}

type NullableDynamicVariableSelectorSettings struct {
	value *DynamicVariableSelectorSettings
	isSet bool
}

func (v NullableDynamicVariableSelectorSettings) Get() *DynamicVariableSelectorSettings {
	return v.value
}

func (v *NullableDynamicVariableSelectorSettings) Set(val *DynamicVariableSelectorSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableDynamicVariableSelectorSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableDynamicVariableSelectorSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDynamicVariableSelectorSettings(val *DynamicVariableSelectorSettings) *NullableDynamicVariableSelectorSettings {
	return &NullableDynamicVariableSelectorSettings{value: val, isSet: true}
}

func (v NullableDynamicVariableSelectorSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDynamicVariableSelectorSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
