/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the ChartWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartWidget{}

// ChartWidget Widget for displaying charts
type ChartWidget struct {
	// Chart title
	Title *string `json:"title,omitempty"`
	// Type of chart
	ChartType       *string                     `json:"chartType,omitempty"`
	Expression      *ChartWidgetExpression      `json:"expression,omitempty"`
	DisplaySettings *ChartWidgetDisplaySettings `json:"displaySettings,omitempty"`
}

// NewChartWidget instantiates a new ChartWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartWidget() *ChartWidget {
	this := ChartWidget{}
	var chartType string = "line"
	this.ChartType = &chartType
	return &this
}

// NewChartWidgetWithDefaults instantiates a new ChartWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartWidgetWithDefaults() *ChartWidget {
	this := ChartWidget{}
	var chartType string = "line"
	this.ChartType = &chartType
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ChartWidget) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidget) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ChartWidget) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ChartWidget) SetTitle(v string) {
	o.Title = &v
}

// GetChartType returns the ChartType field value if set, zero value otherwise.
func (o *ChartWidget) GetChartType() string {
	if o == nil || IsNil(o.ChartType) {
		var ret string
		return ret
	}
	return *o.ChartType
}

// GetChartTypeOk returns a tuple with the ChartType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidget) GetChartTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ChartType) {
		return nil, false
	}
	return o.ChartType, true
}

// HasChartType returns a boolean if a field has been set.
func (o *ChartWidget) HasChartType() bool {
	if o != nil && !IsNil(o.ChartType) {
		return true
	}

	return false
}

// SetChartType gets a reference to the given string and assigns it to the ChartType field.
func (o *ChartWidget) SetChartType(v string) {
	o.ChartType = &v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *ChartWidget) GetExpression() ChartWidgetExpression {
	if o == nil || IsNil(o.Expression) {
		var ret ChartWidgetExpression
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidget) GetExpressionOk() (*ChartWidgetExpression, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *ChartWidget) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given ChartWidgetExpression and assigns it to the Expression field.
func (o *ChartWidget) SetExpression(v ChartWidgetExpression) {
	o.Expression = &v
}

// GetDisplaySettings returns the DisplaySettings field value if set, zero value otherwise.
func (o *ChartWidget) GetDisplaySettings() ChartWidgetDisplaySettings {
	if o == nil || IsNil(o.DisplaySettings) {
		var ret ChartWidgetDisplaySettings
		return ret
	}
	return *o.DisplaySettings
}

// GetDisplaySettingsOk returns a tuple with the DisplaySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartWidget) GetDisplaySettingsOk() (*ChartWidgetDisplaySettings, bool) {
	if o == nil || IsNil(o.DisplaySettings) {
		return nil, false
	}
	return o.DisplaySettings, true
}

// HasDisplaySettings returns a boolean if a field has been set.
func (o *ChartWidget) HasDisplaySettings() bool {
	if o != nil && !IsNil(o.DisplaySettings) {
		return true
	}

	return false
}

// SetDisplaySettings gets a reference to the given ChartWidgetDisplaySettings and assigns it to the DisplaySettings field.
func (o *ChartWidget) SetDisplaySettings(v ChartWidgetDisplaySettings) {
	o.DisplaySettings = &v
}

func (o ChartWidget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.ChartType) {
		toSerialize["chartType"] = o.ChartType
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.DisplaySettings) {
		toSerialize["displaySettings"] = o.DisplaySettings
	}
	return toSerialize, nil
}

type NullableChartWidget struct {
	value *ChartWidget
	isSet bool
}

func (v NullableChartWidget) Get() *ChartWidget {
	return v.value
}

func (v *NullableChartWidget) Set(val *ChartWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableChartWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableChartWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartWidget(val *ChartWidget) *NullableChartWidget {
	return &NullableChartWidget{value: val, isSet: true}
}

func (v NullableChartWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
