/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MarkdownWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarkdownWidget{}

// MarkdownWidget Widget for displaying markdown content. Supports any markdown that is compatible with the CommonMark (https://commonmark.org/) format.
type MarkdownWidget struct {
	// Markdown content
	Content string `json:"content"`
}

type _MarkdownWidget MarkdownWidget

// NewMarkdownWidget instantiates a new MarkdownWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarkdownWidget(content string) *MarkdownWidget {
	this := MarkdownWidget{}
	this.Content = content
	return &this
}

// NewMarkdownWidgetWithDefaults instantiates a new MarkdownWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarkdownWidgetWithDefaults() *MarkdownWidget {
	this := MarkdownWidget{}
	return &this
}

// GetContent returns the Content field value
func (o *MarkdownWidget) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *MarkdownWidget) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *MarkdownWidget) SetContent(v string) {
	o.Content = v
}

func (o MarkdownWidget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarkdownWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *MarkdownWidget) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMarkdownWidget := _MarkdownWidget{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMarkdownWidget)

	if err != nil {
		return err
	}

	*o = MarkdownWidget(varMarkdownWidget)

	return err
}

type NullableMarkdownWidget struct {
	value *MarkdownWidget
	isSet bool
}

func (v NullableMarkdownWidget) Get() *MarkdownWidget {
	return v.value
}

func (v *NullableMarkdownWidget) Set(val *MarkdownWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableMarkdownWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableMarkdownWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarkdownWidget(val *MarkdownWidget) *NullableMarkdownWidget {
	return &NullableMarkdownWidget{value: val, isSet: true}
}

func (v NullableMarkdownWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarkdownWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
