/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the GlobalSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GlobalSettings{}

// GlobalSettings Global display settings
type GlobalSettings struct {
	// Precision for numeric values
	ValuePrecision *int64 `json:"valuePrecision,omitempty"`
	// Font size for display
	FontSize *string `json:"fontSize,omitempty"`
	// Column that can be filtered
	FilterableColumn *string `json:"filterableColumn,omitempty"`
	// Optional unit override for the displayed value.
	UnitOverride *string `json:"unitOverride,omitempty"`
}

// NewGlobalSettings instantiates a new GlobalSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGlobalSettings() *GlobalSettings {
	this := GlobalSettings{}
	var valuePrecision int64 = 0
	this.ValuePrecision = &valuePrecision
	return &this
}

// NewGlobalSettingsWithDefaults instantiates a new GlobalSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGlobalSettingsWithDefaults() *GlobalSettings {
	this := GlobalSettings{}
	var valuePrecision int64 = 0
	this.ValuePrecision = &valuePrecision
	return &this
}

// GetValuePrecision returns the ValuePrecision field value if set, zero value otherwise.
func (o *GlobalSettings) GetValuePrecision() int64 {
	if o == nil || IsNil(o.ValuePrecision) {
		var ret int64
		return ret
	}
	return *o.ValuePrecision
}

// GetValuePrecisionOk returns a tuple with the ValuePrecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalSettings) GetValuePrecisionOk() (*int64, bool) {
	if o == nil || IsNil(o.ValuePrecision) {
		return nil, false
	}
	return o.ValuePrecision, true
}

// HasValuePrecision returns a boolean if a field has been set.
func (o *GlobalSettings) HasValuePrecision() bool {
	if o != nil && !IsNil(o.ValuePrecision) {
		return true
	}

	return false
}

// SetValuePrecision gets a reference to the given int64 and assigns it to the ValuePrecision field.
func (o *GlobalSettings) SetValuePrecision(v int64) {
	o.ValuePrecision = &v
}

// GetFontSize returns the FontSize field value if set, zero value otherwise.
func (o *GlobalSettings) GetFontSize() string {
	if o == nil || IsNil(o.FontSize) {
		var ret string
		return ret
	}
	return *o.FontSize
}

// GetFontSizeOk returns a tuple with the FontSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalSettings) GetFontSizeOk() (*string, bool) {
	if o == nil || IsNil(o.FontSize) {
		return nil, false
	}
	return o.FontSize, true
}

// HasFontSize returns a boolean if a field has been set.
func (o *GlobalSettings) HasFontSize() bool {
	if o != nil && !IsNil(o.FontSize) {
		return true
	}

	return false
}

// SetFontSize gets a reference to the given string and assigns it to the FontSize field.
func (o *GlobalSettings) SetFontSize(v string) {
	o.FontSize = &v
}

// GetFilterableColumn returns the FilterableColumn field value if set, zero value otherwise.
func (o *GlobalSettings) GetFilterableColumn() string {
	if o == nil || IsNil(o.FilterableColumn) {
		var ret string
		return ret
	}
	return *o.FilterableColumn
}

// GetFilterableColumnOk returns a tuple with the FilterableColumn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalSettings) GetFilterableColumnOk() (*string, bool) {
	if o == nil || IsNil(o.FilterableColumn) {
		return nil, false
	}
	return o.FilterableColumn, true
}

// HasFilterableColumn returns a boolean if a field has been set.
func (o *GlobalSettings) HasFilterableColumn() bool {
	if o != nil && !IsNil(o.FilterableColumn) {
		return true
	}

	return false
}

// SetFilterableColumn gets a reference to the given string and assigns it to the FilterableColumn field.
func (o *GlobalSettings) SetFilterableColumn(v string) {
	o.FilterableColumn = &v
}

// GetUnitOverride returns the UnitOverride field value if set, zero value otherwise.
func (o *GlobalSettings) GetUnitOverride() string {
	if o == nil || IsNil(o.UnitOverride) {
		var ret string
		return ret
	}
	return *o.UnitOverride
}

// GetUnitOverrideOk returns a tuple with the UnitOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalSettings) GetUnitOverrideOk() (*string, bool) {
	if o == nil || IsNil(o.UnitOverride) {
		return nil, false
	}
	return o.UnitOverride, true
}

// HasUnitOverride returns a boolean if a field has been set.
func (o *GlobalSettings) HasUnitOverride() bool {
	if o != nil && !IsNil(o.UnitOverride) {
		return true
	}

	return false
}

// SetUnitOverride gets a reference to the given string and assigns it to the UnitOverride field.
func (o *GlobalSettings) SetUnitOverride(v string) {
	o.UnitOverride = &v
}

func (o GlobalSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GlobalSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ValuePrecision) {
		toSerialize["valuePrecision"] = o.ValuePrecision
	}
	if !IsNil(o.FontSize) {
		toSerialize["fontSize"] = o.FontSize
	}
	if !IsNil(o.FilterableColumn) {
		toSerialize["filterableColumn"] = o.FilterableColumn
	}
	if !IsNil(o.UnitOverride) {
		toSerialize["unitOverride"] = o.UnitOverride
	}
	return toSerialize, nil
}

type NullableGlobalSettings struct {
	value *GlobalSettings
	isSet bool
}

func (v NullableGlobalSettings) Get() *GlobalSettings {
	return v.value
}

func (v *NullableGlobalSettings) Set(val *GlobalSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableGlobalSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableGlobalSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGlobalSettings(val *GlobalSettings) *NullableGlobalSettings {
	return &NullableGlobalSettings{value: val, isSet: true}
}

func (v NullableGlobalSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGlobalSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
