/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the DashboardSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardSettings{}

// DashboardSettings Dashboard-wide settings
type DashboardSettings struct {
	// Default time range for the dashboard
	DefaultTimeRange *string `json:"defaultTimeRange,omitempty"`
	// Whether to hide the global environment selector
	HideGlobalEnvironmentSelector *bool `json:"hideGlobalEnvironmentSelector,omitempty"`
}

// NewDashboardSettings instantiates a new DashboardSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardSettings() *DashboardSettings {
	this := DashboardSettings{}
	var hideGlobalEnvironmentSelector bool = false
	this.HideGlobalEnvironmentSelector = &hideGlobalEnvironmentSelector
	return &this
}

// NewDashboardSettingsWithDefaults instantiates a new DashboardSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardSettingsWithDefaults() *DashboardSettings {
	this := DashboardSettings{}
	var hideGlobalEnvironmentSelector bool = false
	this.HideGlobalEnvironmentSelector = &hideGlobalEnvironmentSelector
	return &this
}

// GetDefaultTimeRange returns the DefaultTimeRange field value if set, zero value otherwise.
func (o *DashboardSettings) GetDefaultTimeRange() string {
	if o == nil || IsNil(o.DefaultTimeRange) {
		var ret string
		return ret
	}
	return *o.DefaultTimeRange
}

// GetDefaultTimeRangeOk returns a tuple with the DefaultTimeRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSettings) GetDefaultTimeRangeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultTimeRange) {
		return nil, false
	}
	return o.DefaultTimeRange, true
}

// HasDefaultTimeRange returns a boolean if a field has been set.
func (o *DashboardSettings) HasDefaultTimeRange() bool {
	if o != nil && !IsNil(o.DefaultTimeRange) {
		return true
	}

	return false
}

// SetDefaultTimeRange gets a reference to the given string and assigns it to the DefaultTimeRange field.
func (o *DashboardSettings) SetDefaultTimeRange(v string) {
	o.DefaultTimeRange = &v
}

// GetHideGlobalEnvironmentSelector returns the HideGlobalEnvironmentSelector field value if set, zero value otherwise.
func (o *DashboardSettings) GetHideGlobalEnvironmentSelector() bool {
	if o == nil || IsNil(o.HideGlobalEnvironmentSelector) {
		var ret bool
		return ret
	}
	return *o.HideGlobalEnvironmentSelector
}

// GetHideGlobalEnvironmentSelectorOk returns a tuple with the HideGlobalEnvironmentSelector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSettings) GetHideGlobalEnvironmentSelectorOk() (*bool, bool) {
	if o == nil || IsNil(o.HideGlobalEnvironmentSelector) {
		return nil, false
	}
	return o.HideGlobalEnvironmentSelector, true
}

// HasHideGlobalEnvironmentSelector returns a boolean if a field has been set.
func (o *DashboardSettings) HasHideGlobalEnvironmentSelector() bool {
	if o != nil && !IsNil(o.HideGlobalEnvironmentSelector) {
		return true
	}

	return false
}

// SetHideGlobalEnvironmentSelector gets a reference to the given bool and assigns it to the HideGlobalEnvironmentSelector field.
func (o *DashboardSettings) SetHideGlobalEnvironmentSelector(v bool) {
	o.HideGlobalEnvironmentSelector = &v
}

func (o DashboardSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefaultTimeRange) {
		toSerialize["defaultTimeRange"] = o.DefaultTimeRange
	}
	if !IsNil(o.HideGlobalEnvironmentSelector) {
		toSerialize["hideGlobalEnvironmentSelector"] = o.HideGlobalEnvironmentSelector
	}
	return toSerialize, nil
}

type NullableDashboardSettings struct {
	value *DashboardSettings
	isSet bool
}

func (v NullableDashboardSettings) Get() *DashboardSettings {
	return v.value
}

func (v *NullableDashboardSettings) Set(val *DashboardSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardSettings(val *DashboardSettings) *NullableDashboardSettings {
	return &NullableDashboardSettings{value: val, isSet: true}
}

func (v NullableDashboardSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
