/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"encoding/json"
)

// checks if the StatDisplaySettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatDisplaySettings{}

// StatDisplaySettings Display settings for stat widget
type StatDisplaySettings struct {
	// Settings for value display
	ValueSettings []ValueSettings `json:"valueSettings,omitempty"`
	// Settings for columns
	ColumnSettings []ColumnVisualSetting `json:"columnSettings,omitempty"`
	GlobalSettings *GlobalSettings       `json:"globalSettings,omitempty"`
}

// NewStatDisplaySettings instantiates a new StatDisplaySettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatDisplaySettings() *StatDisplaySettings {
	this := StatDisplaySettings{}
	return &this
}

// NewStatDisplaySettingsWithDefaults instantiates a new StatDisplaySettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatDisplaySettingsWithDefaults() *StatDisplaySettings {
	this := StatDisplaySettings{}
	return &this
}

// GetValueSettings returns the ValueSettings field value if set, zero value otherwise.
func (o *StatDisplaySettings) GetValueSettings() []ValueSettings {
	if o == nil || IsNil(o.ValueSettings) {
		var ret []ValueSettings
		return ret
	}
	return o.ValueSettings
}

// GetValueSettingsOk returns a tuple with the ValueSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatDisplaySettings) GetValueSettingsOk() ([]ValueSettings, bool) {
	if o == nil || IsNil(o.ValueSettings) {
		return nil, false
	}
	return o.ValueSettings, true
}

// HasValueSettings returns a boolean if a field has been set.
func (o *StatDisplaySettings) HasValueSettings() bool {
	if o != nil && !IsNil(o.ValueSettings) {
		return true
	}

	return false
}

// SetValueSettings gets a reference to the given []ValueSettings and assigns it to the ValueSettings field.
func (o *StatDisplaySettings) SetValueSettings(v []ValueSettings) {
	o.ValueSettings = v
}

// GetColumnSettings returns the ColumnSettings field value if set, zero value otherwise.
func (o *StatDisplaySettings) GetColumnSettings() []ColumnVisualSetting {
	if o == nil || IsNil(o.ColumnSettings) {
		var ret []ColumnVisualSetting
		return ret
	}
	return o.ColumnSettings
}

// GetColumnSettingsOk returns a tuple with the ColumnSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatDisplaySettings) GetColumnSettingsOk() ([]ColumnVisualSetting, bool) {
	if o == nil || IsNil(o.ColumnSettings) {
		return nil, false
	}
	return o.ColumnSettings, true
}

// HasColumnSettings returns a boolean if a field has been set.
func (o *StatDisplaySettings) HasColumnSettings() bool {
	if o != nil && !IsNil(o.ColumnSettings) {
		return true
	}

	return false
}

// SetColumnSettings gets a reference to the given []ColumnVisualSetting and assigns it to the ColumnSettings field.
func (o *StatDisplaySettings) SetColumnSettings(v []ColumnVisualSetting) {
	o.ColumnSettings = v
}

// GetGlobalSettings returns the GlobalSettings field value if set, zero value otherwise.
func (o *StatDisplaySettings) GetGlobalSettings() GlobalSettings {
	if o == nil || IsNil(o.GlobalSettings) {
		var ret GlobalSettings
		return ret
	}
	return *o.GlobalSettings
}

// GetGlobalSettingsOk returns a tuple with the GlobalSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatDisplaySettings) GetGlobalSettingsOk() (*GlobalSettings, bool) {
	if o == nil || IsNil(o.GlobalSettings) {
		return nil, false
	}
	return o.GlobalSettings, true
}

// HasGlobalSettings returns a boolean if a field has been set.
func (o *StatDisplaySettings) HasGlobalSettings() bool {
	if o != nil && !IsNil(o.GlobalSettings) {
		return true
	}

	return false
}

// SetGlobalSettings gets a reference to the given GlobalSettings and assigns it to the GlobalSettings field.
func (o *StatDisplaySettings) SetGlobalSettings(v GlobalSettings) {
	o.GlobalSettings = &v
}

func (o StatDisplaySettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatDisplaySettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ValueSettings) {
		toSerialize["valueSettings"] = o.ValueSettings
	}
	if !IsNil(o.ColumnSettings) {
		toSerialize["columnSettings"] = o.ColumnSettings
	}
	if !IsNil(o.GlobalSettings) {
		toSerialize["globalSettings"] = o.GlobalSettings
	}
	return toSerialize, nil
}

type NullableStatDisplaySettings struct {
	value *StatDisplaySettings
	isSet bool
}

func (v NullableStatDisplaySettings) Get() *StatDisplaySettings {
	return v.value
}

func (v *NullableStatDisplaySettings) Set(val *StatDisplaySettings) {
	v.value = val
	v.isSet = true
}

func (v NullableStatDisplaySettings) IsSet() bool {
	return v.isSet
}

func (v *NullableStatDisplaySettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatDisplaySettings(val *StatDisplaySettings) *NullableStatDisplaySettings {
	return &NullableStatDisplaySettings{value: val, isSet: true}
}

func (v NullableStatDisplaySettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatDisplaySettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
