/*
Metoro API

API for managing Metoro environments, alerts, and dashboards.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publicapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GaugeWidgetExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GaugeWidgetExpression{}

// GaugeWidgetExpression Query expression for gauge data
type GaugeWidgetExpression struct {
	MetoroQLQuery *MetoroQLQuery `json:"metoroQLQuery,omitempty"`
	// Aggregation method
	ReduceAggregation string `json:"reduceAggregation"`
}

type _GaugeWidgetExpression GaugeWidgetExpression

// NewGaugeWidgetExpression instantiates a new GaugeWidgetExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGaugeWidgetExpression(reduceAggregation string) *GaugeWidgetExpression {
	this := GaugeWidgetExpression{}
	this.ReduceAggregation = reduceAggregation
	return &this
}

// NewGaugeWidgetExpressionWithDefaults instantiates a new GaugeWidgetExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGaugeWidgetExpressionWithDefaults() *GaugeWidgetExpression {
	this := GaugeWidgetExpression{}
	return &this
}

// GetMetoroQLQuery returns the MetoroQLQuery field value if set, zero value otherwise.
func (o *GaugeWidgetExpression) GetMetoroQLQuery() MetoroQLQuery {
	if o == nil || IsNil(o.MetoroQLQuery) {
		var ret MetoroQLQuery
		return ret
	}
	return *o.MetoroQLQuery
}

// GetMetoroQLQueryOk returns a tuple with the MetoroQLQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GaugeWidgetExpression) GetMetoroQLQueryOk() (*MetoroQLQuery, bool) {
	if o == nil || IsNil(o.MetoroQLQuery) {
		return nil, false
	}
	return o.MetoroQLQuery, true
}

// HasMetoroQLQuery returns a boolean if a field has been set.
func (o *GaugeWidgetExpression) HasMetoroQLQuery() bool {
	if o != nil && !IsNil(o.MetoroQLQuery) {
		return true
	}

	return false
}

// SetMetoroQLQuery gets a reference to the given MetoroQLQuery and assigns it to the MetoroQLQuery field.
func (o *GaugeWidgetExpression) SetMetoroQLQuery(v MetoroQLQuery) {
	o.MetoroQLQuery = &v
}

// GetReduceAggregation returns the ReduceAggregation field value
func (o *GaugeWidgetExpression) GetReduceAggregation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReduceAggregation
}

// GetReduceAggregationOk returns a tuple with the ReduceAggregation field value
// and a boolean to check if the value has been set.
func (o *GaugeWidgetExpression) GetReduceAggregationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReduceAggregation, true
}

// SetReduceAggregation sets field value
func (o *GaugeWidgetExpression) SetReduceAggregation(v string) {
	o.ReduceAggregation = v
}

func (o GaugeWidgetExpression) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GaugeWidgetExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetoroQLQuery) {
		toSerialize["metoroQLQuery"] = o.MetoroQLQuery
	}
	toSerialize["reduceAggregation"] = o.ReduceAggregation
	return toSerialize, nil
}

func (o *GaugeWidgetExpression) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reduceAggregation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGaugeWidgetExpression := _GaugeWidgetExpression{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGaugeWidgetExpression)

	if err != nil {
		return err
	}

	*o = GaugeWidgetExpression(varGaugeWidgetExpression)

	return err
}

type NullableGaugeWidgetExpression struct {
	value *GaugeWidgetExpression
	isSet bool
}

func (v NullableGaugeWidgetExpression) Get() *GaugeWidgetExpression {
	return v.value
}

func (v *NullableGaugeWidgetExpression) Set(val *GaugeWidgetExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableGaugeWidgetExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableGaugeWidgetExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGaugeWidgetExpression(val *GaugeWidgetExpression) *NullableGaugeWidgetExpression {
	return &NullableGaugeWidgetExpression{value: val, isSet: true}
}

func (v NullableGaugeWidgetExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGaugeWidgetExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
